### ISSUE TITLE
Allow App Runner services to talk to AWS resources in a private Amazon VPC

### ISSUE THREAD

**Issue by akshayram-wolverine** [aws/apprunner-roadmap#1]
**Community Note**

- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Customers can run services on App Runner and talk to other AWS services via a public endpoint. For instances, they can talk to Amazon DynamoDB, Aurora DB with public access.  But customers may also want App Runner services to access resources such as RDS instances in a private VPC.

**Comment by adilnaimi** [comment]
just waiting for this to happen, and we will migrate all our ECS workers to App runner

**Comment by Migu33l** [comment]
Same here, I had a lot of Fargate services, but I need to connect to RDS.

Need this before migrating to App Runner.

**Comment by raghibfaisal** [comment]
Was also wondering if there would be a way to reference the app somehow in another security group. For instance, if we have a database running on an EC2 server and want to allow **just** the app (app runner container) to access the EC2-database. The container  in App-Runner does not have a security group in front of it unlike Fargate. Otherwise, we could have referenced the containers security group in the EC2-databases security group.

**Comment by greenreign** [comment]
I know it's been only a month since GA but is there any idea on timing for the next release which hopefully contains this issue?  We can't wait to get off of K8s/EKS and are looking at ECS Fargate but would love to jump straight into AppRunner.  But we need to connect to RDS so I'd really like to understand the potential timing on this.

**Comment by shorn** [comment]
> But we need to connect to RDS ...

This is also my use-case and it's not the first time I've ruled out new AWS tech because it can't interact with RDS or other resources running in my private VPC.

It was literally the first thing I looked at when AppRunner was announced - and this issue absolutely **should be in the FAQ**.  It seems like a general problem that AWS product releases of new tech often come out without the ability to talk to private VPC resources.  

OTOH, it's totally understandable. The team is trying to release cool new tech and so they reduce the scope to a Minimal Viable Product.  It's an unfortunate reality that the MVP approach often makes new AWS technologies unusable for many folks (and not just because of the private VPC resource issue either).

I wonder if it's not time for AWS to come up with a general way for customers to safely connect to private resources - some kind of "reverse VPC endpoint".  Though just writing out the idea of making my RDS accessible this way is giving me the security-heebie-jeebies.

**Comment by 1oglop1** [comment]
How is this not a thing?!
I spent 2 days creating an image and convincing team to get on app runner because it's as good as GCP Cloud Run.
And this MUST HAVE functionality is missing, so I just expose the RDS to the whole internet?

There wasn't any available information about this!

**Comment by 1oglop1** [comment]
@shorn 
Is it not possible?
I was in impression that I just create VPC and security group endpoint for Apprunner and RDS

rds-ep -> rds-ep-sg
apprunner-ep -> apprunner-sg

Rules:
`rds-ep-sg` `ACCEPT` `TCP:5432 (postgres) `from `apprunner-sg`
Is this not how it should work, if not please correct me I'm bit lost in Networking here

**Comment by alexpaluzzi** [comment]
> @shorn
> Is it not possible?
> I was in impression that I just create VPC and security group endpoint for Apprunner and RDS
> 
> rds-ep -> rds-ep-sg
> apprunner-ep -> apprunner-sg
> 
> Rules:
> `rds-ep-sg` `ACCEPT` `TCP:5432 (postgres) `from `apprunner-sg`
> Is this not how it should work, if not please correct me I'm bit lost in Networking here

How would you connect the specific App Runner service with this security group or endpoint? That's a missing piece here.

**Comment by Simbul** [comment]
I found this thread as I also tried adding a DB and was incredibly surprised to realise it wasn't possible.

A bit more research led me to [AWS Copilot](https://aws.github.io/copilot-cli/), which is a slightly more advanced toolkit for containerised apps. Copilot's [Load Balanced Web Service](https://aws.github.io/copilot-cli/docs/concepts/services/#load-balanced-web-service) option was what I needed in the end (i.e. running a containerised app with access to a DB).

Also worth noting that Copilot's [Request-driven Web Service](https://aws.github.io/copilot-cli/docs/concepts/services/#request-driven-web-service) uses App Runner under the hood.

**Comment by 1oglop1** [comment]
@Simbul Yeah I did not use Copilot because it's cloudformation and ECS, I can build the same thing myself using terraform/pulumi and have more control.
I was surprised that Copilot created ECS cluster even then when I created Request driven service which does not need it.

**Comment by dyaacov** [comment]
I spent 3 days trying to connect DocumentDB and ElasticCache to my new App Runner... :(

**Comment by elstr** [comment]
> I spent 3 days trying to connect DocumentDB and ElasticCache to my new App Runner... :(

How did you connect elasticache with app runner? I can't stablish connection, I'm getting timeout :(

**Comment by alexpaluzzi** [comment]
> > I spent 3 days trying to connect DocumentDB and ElasticCache to my new App Runner... :(
> 
> How did you connect elasticache with app runner? I can't stablish connection, I'm getting timeout :(

You can't. That's what this issue is about. They're working on it.

**Comment by dyaacov** [comment]
like the post says... currently it's impossible

I ended up with ECS+Fargate using copilot



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/24/21,
10:52:10 PM

**Comment by akshayram-wolverine** [comment]
Thank you for all the feedback. We are working on VPC support for App Runner and will have more updates on this thread going forward. 

In the meantime as suggested by the community on this thread you can use ECS/Fargate that has access to resources in your VPC by default. You can optionally use Copilot with ECS/Fargate to help simplify the provisioning steps. Copilot also works with App Runner so you can seamlessly migrate to App Runner once VPC support is enabled. For a database choice with App Runner today, you can use [DynamoDB](https://www.apprunnerworkshop.com/intermediate/prereqs/clone/) if it meets your use case. 

To help us better learn about your use case please give us feedback if possible by selecting from the options below that is most consistent with your setup: 

**I plan to use App Runner for** 
1. New greenfield applications 
2. Migrate existing applications from EC2, ECS, Other (tell us)
3. Both (2) & (3) 

**I need VPC support to**:  
1. Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC. 
2. Connect App Runner services to another EKS or ECS service behind a load balancer or a service running on EC2 behind an Load balancer in a VPC 
3. Other (Please tell us) 

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**
1. Often 
2. Sometimes 
3. Rarely 

**Do you use [VPC Flow logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html) today:** 
1. Yes, I use VPC flow logs
2. No, I don't use VPC flow logs

**Comment by alexanderwink** [comment]
- I plan to use App Runner for 1 & 2 (migrating from EC2)
- I need VPC support to 1. Connect App Runner services to RDS databases
- More than one App Runner service talking to the same database/cache 2. sometimes
- Do you use VPC Flow logs today 2. No, I don't use VPC flow logs

**Comment by mheers** [comment]
- I plan to use App Runner for: New greenfield applications
- I need VPC support to: Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC
- Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance: sometimes
- Do you use VPC Flow logs today: No, I don't use VPC flow logs

**Comment by anthonybouton** [comment]
- I plan to use App Runner for: Migrate existing applications from EC2, ECS, Other (tell us)
- I need VPC support to: Connect App Runner services to RDS
- Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance: yes
- Do you use VPC Flow logs today 2. No, I don't use VPC flow logs

**Comment by cou929** [comment]
- New greenfield applications
- Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.
- Sometimes
- No, I don't use VPC flow logs

**Comment by bram-abe** [comment]
*I plan to use App Runner for*

Both

*I need VPC support to*

Connect App Runner services to databases or caches eg. RDS, Elasticache,
DocumentDB that default to a VPC

*Do you foresee more than one App Runner service talking to the same
database/cache by sharing the subnet and security group eg. Three App
Runner services talking to the same RDS instanc*

Sometimes

*Do you use VPC Flow logs
<https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html> today*

No, I don't use VPC flow logs

**Comment by himorishige** [comment]
- I plan to use App Runner for: New greenfield applications
- I need VPC support to: Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC
- Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance: sometimes
- Do you use VPC Flow logs today: No, I don't use VPC flow logs

**Comment by yyoda** [comment]
- I plan to use App Runner for: Both
- I need VPC support to: Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC
- Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance: Rarely
- Do you use VPC Flow logs today: No, I don't use VPC flow logs

**Comment by masteinhauser** [comment]
* I plan to use App Runner for: Both
* I need VPC support to: Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC
* Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance: Rarely
* Do you use VPC Flow logs today: Yes, I use VPC flow logs

**Comment by umm0n** [comment]
I plan to use App Runner for: Migrate existing apps from Beanstalk
I need VPC support to: Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC
Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance: Yes, often
Do you use VPC Flow logs today: No

**Comment by greenreign** [comment]
- I plan to use App Runner for
Migrate existing applications from EKS, K8S
- I need VPC support to:
Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.

- Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance
Often
- No, I don't use VPC flow logs

**Comment by saintech** [comment]
**I plan to use App Runner for**

1. New greenfield applications

**I need VPC support to**:

1. Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.
2. Connect App Runner services to another EKS or ECS service behind a load balancer or a service running on EC2 behind an Load balancer in a VPC

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**

1. Often

**Do you use [VPC Flow logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html) today:**

2. No, I don't use VPC flow logs

**Comment by RichiCoder1** [comment]
* I plan to use App Runner for 1 & 2 (migrating from EC2)
* I need VPC support to 1 & 2. Connect App Runner services to RDS databases, Elasticache, other services 
* 1 & 3: Often talk to same cache, rarely talk to same DB
* Do you use VPC Flow logs today: No, I don't use VPC flow logs

**Comment by alexpaluzzi** [comment]
**I plan to use App Runner for**
Both new and existing application. Existing are mostly in Lambda and Beanstalk.

**I need VPC support to:**
Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**
Yes. Often.

**Do you use VPC Flow logs today:**
No, I don't use VPC flow logs

**Comment by baer** [comment]
**I plan to use App Runner for**
Migrate existing applications from Elastic Beanstalk.

**I need VPC support to:**
Our VPC has private subnets that use an AWS Site-to-Site VPN to access internal resources. Our application needs access to those resources. Roughly, [this](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario3.html) is our configuration. The most important connection is a SQL Server Database running in Azure.

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**
Unlikely. However, we deploy with [CDK](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apprunner-readme.html) our services and, most often, we do not specify the subnet specifically. I'm not sure if this has any impact, but retention policy and how things are deployed may be a factor.
_Note:_ It looks like a higher-order construct is [not on the roadmap](https://github.com/orgs/aws/projects/7) for CDK at the time of writing. Any help here would be appreciated :).

**Do you use VPC Flow logs today:**
No.

**Comment by amgci** [comment]
I plan to use App Runner for
Migrate existing applications from EC2, ECS, Other (tell us)
I need VPC support to:
Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.
Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance
Sometimes
Do you use VPC Flow logs today:
No, I don't use VPC flow logs
Additional Item – ticket regarding PHP support – very key to our migration to AppRunner
Thanks, Kipp

**Comment by shorn** [comment]
Unsubscribed from this issue since I don't really need a stream of emails telling me that nobody uses VPC flow logs.

**Comment by choreo** [comment]
Should we keep answering the inquiry?  Sorry for bothering all.
**I plan to use App Runner for**
1. New greenfield applications

**I need VPC support to**:
1. Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.
 (Mainly RDS)

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**

2. Sometimes

**Do you use [VPC Flow logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html) today:**

2. No, I don't use VPC flow logs

**Comment by mwarkentin** [comment]
I plan to use App Runner for
3.    Both (1) & (2)

I need VPC support to:

    Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.
    Connect App Runner services to another EKS or ECS service behind a load balancer or a service running on EC2 behind an Load balancer in a VPC

Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance

    Often: we often have multiple services within a single app which all talk to the database, cache, etc - we often have a public web process, internal api process, multiple async worker processes, etc within an application

Do you use VPC Flow logs today:

    Yes, I use VPC flow logs

**Comment by pawelmrowczynski** [comment]
**I plan to use App Runner for**

 - New greenfield applications

I need VPC support to:

 - Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.
 - Access other resources that are available only inside of the vpc

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**
- Often

**Do you use VPC Flow logs today:**
 - No

**Comment by MasatoshiMizumoto** [comment]
I plan to use App Runner for 1 & 2 (migrating from EC2)
I need VPC support to 1. Connect App Runner services to RDS databases
More than one App Runner service talking to the same database/cache 2. sometimes
Do you use VPC Flow logs today 2. No, I don't use VPC flow logs

**Comment by JFDontigny** [comment]
I plan to use App Runner for

- New greenfield applications

I need VPC support to:

- Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.

Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance

- Sometimes

Do you use VPC Flow logs today:

- No, I don't use VPC flow logs

**Comment by davidmcl** [comment]
I plan to use App Runner for:
**BOTH NEW & EXISTING**

I need VPC support to:
Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB; 
**INCLUDING MULTIPLE DATABASES ACROSS MULTIPLE VPCs (but single AWS account).**

Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance
**YES**

Do you use VPC Flow logs today:
**NO**

**Comment by davidmcl** [comment]
> In the meantime as suggested by the community on this thread you can use ECS/Fargate that has access to resources in your VPC by default. ....

_**...but wasn't the whole value-add proposition of apprunner was that you didn't have to and it was easier than the other options?**_

_AWS App Runner is an AWS service that provides a fast, simple, and cost-effective way to deploy from source code or a container image directly to a scalable and secure web application in the AWS Cloud. You don't need to learn new technologies, decide which compute service to use, or know how to provision and configure AWS resources._

Pity it doesn't work for one (or more) of the most common use cases; e.g. an api

**Comment by Velniai** [comment]
I plan to use App Runner for:
**BOTH NEW & EXISTING**

I need VPC support to:
**Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB;**

Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance
**YES**

Do you use VPC Flow logs today:
**NO**

**Comment by RichiCoder1** [comment]
Fingers crossed this drops before/with Re:Invent coming up. This really is the only thing holding us back personally from using App Service for most our use cases.

**Comment by amgci** [comment]
Yes, this and PHP support are the 2 things holding us back from using App Runner.

**Comment by clarksm** [comment]
**I plan to use App Runner for**
Both (1) & (2)

**I need VPC support to:**
Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.
Connect App Runner services to another EKS or ECS service behind a load balancer or a service running on EC2 behind an Load balancer in a VPC

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**
Sometimes

**Do you use VPC Flow logs today:**
Yes, I use VPC flow logs

**Comment by akospinter** [comment]
App Runner is a great product, but I think the VPC / SecurityGroup support is an essential feature.

Do you have any estimation when this feature will be released?

**Comment by akshayram-wolverine** [comment]
Thanks so much for all the feedback!! Really appreciate the time and effort. The feedback has been really helpful to make sure we are building the feature in a way that aligns with customer's expectations. We are heads down working on this and I have moved this to the coming soon section of the roadmap.

**Comment by CarlosDomingues** [comment]
**I plan to use App Runner for**
Both (1) & (2)

**I need VPC support to:**
Connect App Runner services to databases or caches eg. RDS, Elasticache, DocumentDB that default to a VPC.
Connect App Runner services to another EKS or ECS service behind a load balancer or a service running on EC2 behind an Load balancer in a VPC
**Block access from external / non-approved hosts.**

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**
No

**Do you use VPC Flow logs today:**
Yes, I use VPC flow logs

**Comment by abhijitajmera** [comment]
Meanwhile is there any workaround for App Runner communication to Aurora and ElastiCache?

**Comment by DilwoarH** [comment]
> Thanks so much for all the feedback!! Really appreciate the time and effort. The feedback has been really helpful to make sure we are building the feature in a way that aligns with customer's expectations. We are heads down working on this and I have moved this to the coming soon section of the roadmap.

Do you have an estimated time when this will be made available?

**Comment by brown99** [comment]
**I plan to use App Runner for**
Both (1) & (2)

**I need VPC support to:**
* Connect App Runner services to RDS 

**Do you foresee more than one App Runner service talking to the same database/cache by sharing the subnet and security group eg. Three App Runner services talking to the same RDS instance**
Yes

**Do you use VPC Flow logs today:**
No

**Comment by adonig** [comment]
This issue prevents me from converting my Elastic Beanstalk and Elastic Container Service apps to App Runner.

**Comment by mwarkentin** [comment]
Looks like it should be coming soon, there was a `AppRunnerNetworkingServicePolicy` that showed up the other day and has VPC permissions, etc.

**Comment by khalidjaz** [comment]
Has there been any updates on this?

**Comment by mwarkentin** [comment]
@khalidjaz just saw this! https://github.com/aws/copilot-cli/releases/tag/v1.15.0

**Comment by jvisker** [comment]
I don't see an announcement, but I do see the feature in the console.

**Comment by pfeilbr** [comment]
Announcement at https://aws.amazon.com/blogs/aws/new-for-app-runner-vpc-support/

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/apprunner/latest/relnotes/release-2022-02-08-vpc.html

**Comment by vanpeltj** [comment]
Does anyone know when this feature will be integrated in the aws terraform module?

**Comment by fitzoh** [comment]
>Does anyone know when this feature will be integrated in the aws terraform module?

Looks like this is the tracking issue you want: https://github.com/hashicorp/terraform-provider-aws/issues/23090

https://github.com/hashicorp/terraform-provider-aws/search?q=apprunner+vpc&type=issues

**Comment by mwarkentin** [comment]
Looks like it was just released in the [4.4.0 terraform provider](https://github.com/hashicorp/terraform-provider-aws/issues/23173)!

**Comment by dyaacov** [comment]
What about connecting to DocumentDB



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/06/22,
03:41:26 PM

**Comment by jzaplet** [comment]
Hi, I have a simple PHP application deployed via ECR to the App Runner. I successfully connected the App Runner through VPC to a private RDS. However, when I make a request (PHP-CURL) from my application to any public endpoint (outside of AWS), my application crashes on timeouts. My questions is: Where should I allow the App Runner to send requests outside of AWS and still be connected to a private RDS? What settings do I need to make?

**Comment by justiceamoh** [comment]
@jzaplet, I'm having the same issues. Can you share how you resolved this using the NAT Gateway in VPC? If you can point me to a resource, that'd be super helpful. Thanks in advance!

**Comment by MPTG94** [comment]
Hey @justiceamoh, I also needed to enable this functionality, please refer to [this](https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-scenarios.html) resource for NAT gateways and also [this](https://aws.amazon.com/blogs/containers/observability-for-aws-app-runner-vpc-networking/) example from AWS will show you the general process step by step.

One important note you might miss because it is not emphasized enough in the examples - the NAT gateway should be part of a  PUBLIC subnet that is routed to an internet gateway (if you need the App Runner instance to connect to resources in the internet and outside your VPC).
Other than that, the guide should walk you through things in a pretty straightforward manner

**Comment by jenilkukadiya82** [comment]
I am currently working on configuring our App Runner service to communicate with our RDS database. Here’s the detailed scenario:

RDS Database Setup:
We are using an RDS database with the default VPC, subnets, and security groups.
The RDS instance is currently not publicly accessible.
App Runner Configuration:
In the App Runner configuration, under the Networking tab, I want to set up outgoing traffic to use a custom VPC to communicate with the RDS database.
I created a new VPC connector and selected the same VPC, subnets, and security groups that are used by the RDS database.
Issue Encountered:
After configuring the VPC connector and attempting to save the changes, I received the following error: "Delete the active VpcIngressConnections associated with it first."
Can anyone provide guidance on how to fix this issue?

**Comment by stanislavromanov** [comment]
This feature is ridiculous. When you enable VPC for local connections to connect to DB it will connect to DB but then will not be able to access anything outside of local network e.g. send requests to some API endpoint like api.gpt.com etc.

**Comment by stefffdev** [comment]
> This feature is ridiculous. When you enable VPC for local connections to connect to DB it will connect to DB but then will not be able to access anything outside of local network e.g. send requests to some API endpoint like api.gpt.com etc.

This was helpful to me when I faced the same problem: https://stackoverflow.com/questions/74249737/how-to-access-the-internet-from-an-aws-app-runner-service-that-is-added-to-a-vpc
