### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by iselegant** [aws/apprunner-roadmap#10]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
As far as I know, AWS AppRunner currently only supports Python 3.x and Node.js 12.x.
I really want to expect support for Golang applications.

**Comment by snnles** [comment]
App Runner now supports Golang.

https://aws.amazon.com/about-aws/whats-new/2022/10/aws-app-runner-support-php-go-dot-net-ruby-managed-runtimes/

**Comment by Ben-CA** [comment]
Does it still? 
https://github.com/aws/apprunner-roadmap/issues/225#issuecomment-3793009103
