### ISSUE TITLE
Documentation: Clarify how long requests can last

### ISSUE THREAD

**Issue by jvisker** [aws/apprunner-roadmap#101]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Document how long requests can last. Empirically it looks like they are always cut off at 2 minutes, but this repost question and comment seem to indicate 30 seconds (https://repost.aws/questions/QUK3YcHzS6SVCvbF-UkWptOw/app-runner-request-timeout-http-503).

**Comment by suzukieng** [comment]
I have an answer from AWS support that it is currently hard-capped at 30 seconds, and it's a known limitation of AppRunner.
AWS support asked me to open an issue here, which I will do shortly (separately from this one)

**Comment by suzukieng** [comment]
See #104

**Comment by CarlosDomingues** [comment]
Is there any strong reason for 30s timeouts?

That makes App Runner badly suited for workloads that deal with long running jobs, like analytics.

**Comment by keerataws** [comment]
Yes, this is a known limitation at the moment and is a roadmap issue. The service team is working on it. Sorry, if this limitation is causing inconvenience for you.

**Comment by CarlosDomingues** [comment]
@keerataws

Thank you for the quick response. Since this issue has "Documentation" in the title, I thought only documentation was being addressed, which is why I asked about the timeout itself. I'm very happy to know this is also being worked on!

**Comment by snnles** [comment]
Thank you for your feedback. We have updated the request read timeout in App Runner from 30 seconds to 120 seconds. Our documentation has also been updated.

Documentation link: https://docs.aws.amazon.com/apprunner/latest/dg/develop.html#develop.considerations

**Comment by jvisker** [comment]
Thanks @snnles!

**Comment by suzukieng** [comment]
Good stuff, thank you @snnles !
