### ISSUE TITLE
Add concurrency metric

### ISSUE THREAD

**Issue by jvisker** [aws/apprunner-roadmap#103]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add a concurrency metric. App Runner scales based on concurrency so it would be very helpful to see what levels of concurrency are being used. It will be pivotal in tuning the configuration.

**Comment by MrSakhs** [comment]
This will be very useful as autoscaling hinges on this data/metric. 

In the meantime, is there a way this information can be sourced and published using custom metrics or some other way? 
I basically asking for any work around to get this information?

**Comment by jvisker** [comment]
I think just launched: https://aws.amazon.com/about-aws/whats-new/2023/02/aws-app-runner-concurrency-cpu-memory-utilization-metrics/

**Comment by snnles** [comment]
Hello everyone, App Runner now emits service based Concurrency metric in App Runner Console and Amazon CloudWatch. See the launch announcement for more details.
https://aws.amazon.com/about-aws/whats-new/2023/02/aws-app-runner-concurrency-cpu-memory-utilization-metrics/
