### ISSUE TITLE
The number of instances scales to zero.

### ISSUE THREAD

**Issue by fightnyy** [aws/apprunner-roadmap#105]
Hello, AWS App runner developers.
I'm suffering some issues with the number of instances.
I set the instance number of the minimum instances to 1 and the maximum of 25. But as you can see, there is a problem that If there is no request for a certain amount of time the number of instances is set to be zero. And also if the number of instances is set to zero and a request comes in while the number of instances is 0, you can see that request latency takes longer time than usual. So is it normal even though, I set the minimum number of instances to one, but it became zero?
If not, can you give some help to prevent it become zero?
![image](https://user-images.githubusercontent.com/55227984/150975406-e3de19be-76ad-4c6c-84a8-c14ef877e378.png)

**Comment by jvisker** [comment]
You can set the minimum number of inactive instances, not active instances.

**Comment by fightnyy** [comment]
So to sum up, is there no other way to determine the minimum number of active instances?
We want at least one instance always to be Active Instance.
As you can see in the picture, if it the number of instances become 0, the speed of latency became spiked

**Comment by jvisker** [comment]
That graph is correct for the number of **active** instances. However when a provisioned instance becomes idle the CPU is throttled. (You would have one provisioned instance if you have a minimum of 1 instance).

https://aws.amazon.com/apprunner/faqs/

> AWS App Runner monitors the number of concurrent requests sent to your application and automatically adds additional instances based on request volume. If your application receives no incoming requests, App Runner will scale the containers down to a provisioned instance, a cpu throttled instance ready that is ready to serve incoming requests within milliseconds. You can also optionally configure the number of concurrent requests sent to an instance in the autoscaling settings of your application.

Your one provisioned instance that is CPU throttled is an **inactive** instance, but it should be ready to serve traffic in milliseconds according to AWS. So if the traffic dropped off then the "Active Instances" graph is normal. However, you shouldn't have a "cold start", so that would still be worth looking into.

One thing I would make sure is that your container isn't dying (because it is exiting) or being killed (because of failed health checks). It is kind of hard to tell when it happens, but if you have any logs on startup they would show up again when the replacement instance starts.

**Comment by fightnyy** [comment]
Thank you for you answer jvisker!
Now I realized that **Inactive instances are not killed instances(Actually It's a just throttled instance)**.
But as you mentioned, I don't want **cold start** that our users will suffer while they use our apps. 
Even though, there's no request for a while, is there any other option to persist active instance at least one?

**Comment by spesnova** [comment]
@fightnyy 

> Even though, there's no request for a while, is there any other option to persist active instance at least one?

as @jvisker said, basically App Runner's provisioned instance mechanism exists for that use case. Currently App Runner itself doesn't have option to keep instances active without traffic.

But if you really want to keep instance active, you can send HTTP requests periodically with something like CloudWatch Synthetics, Pingdom etc as a workaround. 

Also, I recommend you to try to increase the minimum instances(=provisioned instances) in auto scaling config before trying the above workaround.

**Comment by fightnyy** [comment]
Thank you for your replying!!! @spesnova @jvisker 👍

**Comment by tommydongaws** [comment]
Is there a plan to have a setting for this, instead of a workaround?

**Comment by joowani** [comment]
I am also running into the same issue with a noticeable spike in request latency (8000 milliseconds, not "within milliseconds" as advertised) when the app runner instance is switching from inactive to active. Please see screenshots:

<img width="421" alt="Screenshot 2023-08-07 at 9 40 39 AM" src="https://github.com/aws/apprunner-roadmap/assets/2701938/d44955d0-6dd9-4002-b3c8-22ad5c28b7dd">
<img width="421" alt="Screenshot 2023-08-07 at 9 40 45 AM" src="https://github.com/aws/apprunner-roadmap/assets/2701938/2857d098-930a-49a2-987d-f5dfb16bdf84">
<img width="753" alt="Screenshot 2023-08-07 at 9 45 36 AM" src="https://github.com/aws/apprunner-roadmap/assets/2701938/70656ed2-44e1-4973-96d8-4e8ced2666c4">

So cold start does seem to be a thing here? Would this be dependent on the nature of my app (Django + Postgres + Gunicorn)?
