### ISSUE TITLE
Specify DNS record type explicitly 

### ISSUE THREAD

**Issue by spesnova** [aws/apprunner-roadmap#106]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request** 
Please specify DNS record type as "CNAME" explicitly in the description below.

<img width="1071" alt="AWS_App_Runner" src="https://user-images.githubusercontent.com/261700/151301604-d7781896-fd6f-4a80-ba30-2ce30cc60598.png">

Typically, TXT record is used for DNS validation. So people can misunderstand that App Runner provides TXT records but actually they are CNAME records. 

Some people who're familiar with AWS Certificate Manager might be able to understand they are CNAME records not TXT records ([ACM uses CNAME for the validation](https://docs.aws.amazon.com/acm/latest/userguide/dns-validation.html)). Also the official docs says:

> _When you associate a custom domain with your service, App Runner provides you with a set of CNAME records to add to your Domain Name System (DNS)._

https://docs.aws.amazon.com/apprunner/latest/dg/manage-custom-domains.html

But specifying them explicitly in App Runner Console is more user-friendly for everyone.

**Describe alternatives you've considered**

Adding a new column "Record Type" in addition to the "Record Name" and "Value". 

**Additional context**
Anything else we should know?

An App Runner user told me that they got stuck in the issue before. They were confused about the DNS record type.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

N/A

**Comment by AbraamNader** [comment]
I use cloudflare as a DNS Provider, and as per their documentation the validation records are TXT records.
This is such a simple suggestion that would have saved me two days of waiting for domain validation, then I used the CNAME type as suggested by [spesnova](https://github.com/spesnova) then everything worked fine.

**Comment by alex-pixelverse** [comment]
Have to agree, kind of low-hanging fruit here.

**Comment by kyleliu2022** [comment]
this problem has troubled me for a long time.
 I used the CNAME now,  waiting for verification result 
hope everything is fine

**Comment by alex-pixelverse** [comment]
It is slightly concerning to see such a simple issue going stale after almost a year. It‘s an obvious UX improvement, with zero risk involved, basically a documentation fix.

**Comment by daniel-keller** [comment]
This is still an issue in 2023. At least this Github issue comes up when you google the problem which is what prevented me from hours of headaches.

**Comment by henricook** [comment]
Super simple to fix issues like this that are still hanging around, and no visible interaction from the app runner team is the reason I've decided not to use this service. This kind of standard shouldn't be permitted by AWS.

**Comment by wub** [comment]
It looks like this has been completed.

<img width="494" alt="image" src="https://github.com/aws/apprunner-roadmap/assets/427410/8bc50c5d-837d-4a9e-bbc0-493bf73b5d9d">

**Comment by spesnova** [comment]
@wub 

Thanks for letting us know.
