### ISSUE TITLE
Higher CPU Limit options

### ISSUE THREAD

**Issue by dmacbride-ep** [aws/apprunner-roadmap#107]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Allow containers to be allocated up to 4 CPU cores.

**Describe alternatives you've considered**
Our customers run our application in ECS and EKS now, but struggle to manage those services effectively

**Additional context**
We are a software vendor who sell a solution that our customers self-manage. Ours is a set of containerized Java / Tomcat applications / services that run in orchestration, along with ActiveMQ and RDS. Our customers take on the responsibility to run and operate this solution. Today we provide them some IaC assets to provision an EKS-based environment, with ingress controller, HPA, etc. This approach has proven too complex for our less-mature customers to manage in the long term. We would like them to use something like App Runner instead, but so far it is a non-starter far for several reasons, including the too-low-for-us CPU limit.

**Comment by snnles** [comment]
@dmacbride-ep Thanks for the feedback. We are looking into increasing compute configuration SKUs. With 4 CPU, what compute memory will be ideal for your use case?

**Comment by dmacbride-ep** [comment]
@snnles 
8GB of compute memory would be the ideal max compute memory with 4 cpu cores.

**Comment by itizarsa** [comment]
We are also in need of high CPU & memory configuration in App Runner, due to this we have migrated to Fargate which adds a operational overhead to our team. Would really great if we have options like we have in Fargate for CPU & Memory. At minimum, 4vCPU & 8GB Memory & 8VCPU & 16GB memory would suffice at the moment

**Comment by jayceslesar** [comment]
this would rock -- being able to have the same configuration options as fargate seems pretty organic
