### ISSUE TITLE
When will App Runner be available in ap-southeast-2 ? 

### ISSUE THREAD

**Issue by johancar** [aws/apprunner-roadmap#108]
When will App Runner be available in ap-southeast-2 ?

**Comment by andymac4182** [comment]
This would be awesome. I have a bunch of clients chasing this.

**Comment by wade-onetime** [comment]
Another vote for this one

**Comment by zzdjk6** [comment]
vote up

**Comment by scrolls-mckenzie** [comment]
please

**Comment by snnles** [comment]
Hello everyone, App Runner is now available in ap-southeast-2 (Sydney) region. Please try out App Runner and let us know of any feedback that you may have. Thank you for all your feedback and support.

Launch Announcement - https://aws.amazon.com/about-aws/whats-new/2023/03/aws-app-runner-singapore-frankfurt-sydney-regions/
