### ISSUE TITLE
Make AppRunner available in the Singapore ( ap-southeast-1 ) Region 

### ISSUE THREAD

**Issue by mtiarnan** [aws/apprunner-roadmap#111]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Make AppRunner available in the Singapore ( ap-southeast-1 ) Region or else to know if there's an ETA on when or if AppRunner will be made available in ap-southeast-1

**Describe alternatives you've considered**
N/A

**Additional context**
Anything else we should know?
N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by snnles** [comment]
Hello everyone, App Runner is now available in ap-southeast-1 (Singapore) region. Please try out App Runner and let us know of any feedback that you may have. Thank you for all your feedback and support.

Launch Announcement - https://aws.amazon.com/about-aws/whats-new/2023/03/aws-app-runner-singapore-frankfurt-sydney-regions/
