### ISSUE TITLE
Improve disk storage documentation

### ISSUE THREAD

**Issue by stephanos** [aws/apprunner-roadmap#112]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

The documentation - [AWS App Runner Developer Guide](https://docs.aws.amazon.com/apprunner/latest/dg/apprunner-guide.pdf) - is very vague around disk storage, specifically:

**(1) How much storage is available?**

It's not stated. Is it the [same as for Fargate](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html) (20 GiB)?

**(2) Are there plans to allow increasing the available disk storage?**

I'm interested in 50-100 GiB of ephemeral storage (for caching purposes).

**(3) Why are files not guaranteed to persist beyond the processing of a single request?**

The documentation only has the vague statement "files aren't guaranteed to persist beyond the processing of a single request". It would be great to be able to understand this better. Does that mean _some_ previously stored files just disappear; or _all_ of them? Or that some writes will seemingly work but the file is never actually written to disk?

**Describe alternatives you've considered**

I am aware of the EFS issue https://github.com/aws/apprunner-roadmap/issues/14 but am more interested in ephemeral storage (for its speed).

**Comment by keerataws** [comment]
@stephanos - thank you for these suggestions. I will look at the document suggestions (1 & 3).

**Comment by snnles** [comment]
We have updated our documentation with current capabilities and limitations around ephemeral storage available in App Runner. To summarize - "App Runner provides you with 3 GB of ephemeral storage and uses a part of the 3 GB of ephemeral storage for its pulled, compressed, and the uncompressed container image on the instance."

Check out the '[Developing application code for App Runner](https://docs.aws.amazon.com/apprunner/latest/dg/develop.html)' in the development guide for more details.

**Comment by genzerstech** [comment]
we have a docker image of 8GB in size that runs python code. the docker image is huge because of all the third party modules that we need to use. however, if only 3GB of storage is available, how can we deploy this image in apprunner?
