### ISSUE TITLE
Restrict access to App runner service using security group is not working.

### ISSUE THREAD

**Issue by Dhyanesh97** [aws/apprunner-roadmap#113]
I have created an app runner service and attached security group using VPC connector. 

Here security group is used only to allow app runner to communicate to services within VPC ?
Or it can be used to restrict access to App runner as well ?

My Requirement is to basically setup inbound rules for app runner and don't want it to be publicly accessed.

**Comment by rhbecker** [comment]
Is this need not satisfied via WAF web ACLs?

I realize this issue is about using Security Groups, but the original poster's requirement is stated as ...

> My Requirement is to basically setup inbound rules for app runner and don't want it to be publicly accessed.

I don't have direct experience using WAF web ACLs - my assumption that it can be used to solve this need is based entirely on my understanding of the [App Runner documentation of this feature](https://docs.aws.amazon.com/apprunner/latest/dg/waf.html) and [the blog post announcing its availability](https://aws.amazon.com/about-aws/whats-new/2023/02/aws-app-runner-web-application-firewall-enhanced-security/).

I'm asking because I want to validate my own understanding, as I too have this need.

**Comment by jvisker** [comment]
@snnles I'm just wondering "Coming Soon" is still accurate considering it was marked that way in September.

**Comment by smeera381** [comment]
App Runner supports private endpoints accessible only from within VPC. You can learn more about the feature in the below What's New post and blogposts mentioned in the announcement.

https://aws.amazon.com/about-aws/whats-new/2022/11/aws-app-runner-supports-privately-accessible-services-amazon-vpc/

**Comment by Rileyjrjohns** [comment]
Hello, i'm also quite surprised that app runner is not flexible about networking. For example, i allow some Ip's adress only to access a mongoDB Replica with security group settings. I can't find any option/solution to allow my apprunner to access it without set my sg to allow all ips... It's crucial to have this kind of possibilities.

**Comment by as14692** [comment]
@jsheld  Is it possible to access the AppRunner service from the public internet and use a SG to restrict the incoming traffic? Looks like it supports only private endpoints accessible "only from within the VPC and not from public internet". Please verify.

**Comment by Dhyanesh97** [comment]
@jsheld We want it to be accessed from public internet but with restricted incoming traffic using security group.

**Comment by Rileyjrjohns** [comment]
@as14692 i searched for it, you can't have a static ip or something like that. Or it's maybe possible to do more complex stuff to open it and expose via a static ip inside the vpc. But for a service claiming easy setup, we are quite far 😅

**Comment by as14692** [comment]
> @jsheld We want it to be accessed from public internet but with restricted incoming traffic using security group.

Please reopen the issue if you can.

**Comment by jsheld** [comment]
The recommendation is to use a VPC endpoint and associate the security group with that endpoint accordingly. I believe @smeera381 provided a link to that documentation above.
