### ISSUE TITLE
Support for Node.js 16

### ISSUE THREAD

**Issue by vladshcherbin** [aws/apprunner-roadmap#118]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

It would be great to have nodejs 16 support since it is the LTS version and nodejs 14 is in maintenance status.
Elastic Beanstalk recent update brought nodejs 16 support, would be great to see support in App Runner too.

**Attachments**

Nodejs schedule:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/6711845/157531308-a3651b25-9ecc-437d-b1d5-7bf9849453ea.png">

**Comment by snnles** [comment]
App Runner now supports node.js 16

https://aws.amazon.com/about-aws/whats-new/2022/09/aws-app-runner-supports-node-js-managed-runtime/
