### ISSUE TITLE
Prepare and plan Node 18 deployment schedule

### ISSUE THREAD

**Issue by SirJamesBrown** [aws/apprunner-roadmap#120]
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request

Prepare and plan Node 18 deployment

Node 16 isnt available yet and 18 release is around the corner which will likely be the next LTS. We love app runner but cant use it in active projects unless it's as predictable as EC2. If LTS is minimum viable, knowing ahead of time when scheduled dev and demo is starting would give us all an incentive.

**Comment by 1tonyca** [comment]
Thanks for the interest, active LTS for Node 18 starts on 2022-10-25, per https://nodejs.org/en/about/releases, and we are planning to support it shortly after. We will move this issue out of research card as soon as we start.

**Comment by LucasMoskun** [comment]
Any updates on this?

**Comment by curran** [comment]
Dates for reference:
 * Active LTS start: 2022-10-25
 * Maintenance LTS start: 2023-10-18

**Comment by jsheld** [comment]
The team is currently working on support for NodeJS18. We do not have an ETA just yet. Will update once we do.

**Comment by evansaa1** [comment]
We were hoping to deploy some newly developed NodeJS services on App Runner only to find that it only supports old versions of the Node runtime. Unless I'm missing something App Runner (when deploying directly from a code repo) only gives me the option of Node 12, 14 and 16 and 16 hits end of life next month. 18 has been LTS and 20 has been current since November last year, is AppRunner getting the maintenance attention it needs or should I be considering alternatives?

**Comment by SirJamesBrown** [comment]
I'd like to make a request.
This post started well over a year ago. 18 is about to go into maintenance, 19 came and went and now we're on 20 (arguably a greater update) to be LTS. 
The cycle has been missed with no clarity given. 

My assumption therefor as a customer is that if the clarity given is "soon after" and that is almost a _year_ after, app-runner is either being deprecated, simply ignored or sacrificed to other services.
Point being, I am as unclear now as over a year ago. 

The request was "Prepare and plan Node 18 deployment schedule" but there is no apparent schedule.  
I don't like being a downer but this really is exactly what i was asking to avoid.

The request is, can we confirm if there is a plan to maintain a relative tempo with node or is it ad-hoc if/when time allows?

Could we also get a list of potential alternative solutions on AWS which may be more appropriate or have more active development to ease the load on app-runner if it is struggling under development and support load?

**Comment by nick-ax** [comment]
Move to AWS ECS or EKS. That's what our AWS account rep suggested so we did.

**Comment by ant-roli** [comment]
flightcontrol.dev looks promising. Very similar setup to app runner and deploys to fargate.

**Comment by AbeEstrada** [comment]
Any news? I don't want to deal with server again

**Comment by jsheld** [comment]
The team is currently working on this. We will let you know when we have an update in terms of timeline.

**Comment by jsheld** [comment]
I cannot talk about timelines but please be rest assured that this is currently in progress. Thank you for your patience.

**Comment by gautamsi** [comment]
We now have Node 20 as LTS, There is lot of pain in keeping overridden dependencies which has moved on to Node 18 being minimum version.

**Comment by mr-nagashima** [comment]
Will App Runner continue to be maintained and will I be able to continue using it? Or is it better to use other AWS services?

**Comment by AbeEstrada** [comment]
[AWS Lambda adds support for Node.js 20](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-node-js-20/)

**Comment by marco910** [comment]
Are there any updates on this? We want to run Next.js 14 on AppRunner

**Comment by marco910** [comment]
Just had a look into AWS AppRunner in the `eu-central-1` region and noticed that the Node.js 18 runtime is now available! Didn't check this in other regions, but I think it's the same in other regions where AppRunner is available.

Also tested a Node.js 18 project using Next.js 14 on it and seems to work fine.

**Comment by evansaa1** [comment]
Just in time for Node 18 to no longer be in active support 🙄 App Runner is a joke

**Comment by brunomorency** [comment]
Official announcement: https://docs.aws.amazon.com/apprunner/latest/relnotes/release-2023-12-29-python-node-prebuild.html

Hopefully they’ll add Node 20 quickly based on that work.

**Comment by AbeEstrada** [comment]
For reference: https://docs.aws.amazon.com/apprunner/latest/dg/service-source-code-nodejs-releases.html

**Comment by Adesin-fr** [comment]
Also waiting for Node 20 support...

To others, until we have officla node 20 support, we still can build docker images (but I'm ok, it requires more setup/work than code repo setup...)
