### ISSUE TITLE
HTTP 1.0 support

### ISSUE THREAD

**Issue by electric-al** [aws/apprunner-roadmap#121]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support HTTP 1.0.
This has been added to envoy upstream https://github.com/envoyproxy/envoy/pull/2792

Currently this blocks some server API requests that are stuck at being http 1.0. A good example is a using apprunner as a 'shopify app proxy' target which always uses HTTP 1.0 (and does not look like it updating to http./1.1+ soon)

**Describe alternatives you've considered**
Currently getting this to work by putting a cloudfront distribution in front. However this is more setup that we would like as we will using multiple apprunner instances across different environments. 

**Additional context**
N/A

**Attachments**
N/a

**Comment by itizarsa** [comment]
Hi Folks, Any updates on when this will be picked up by the app runner team?

**Comment by amitgupta85** [comment]
Thanks for your patience. We are going to take a look at this.

**Comment by snnles** [comment]
Thank you everyone for your feedback. App Runner now supports HTTP 1.0 

https://aws-preview.aka.amazon.com/about-aws/whats-new/2023/02/aws-app-runner-http-1-0-protocol/
