### ISSUE TITLE
GA for AWS App Runner in India, Mumbai Region (ap-south-1)

### ISSUE THREAD

**Issue by rambabusaravanan** [aws/apprunner-roadmap#126]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

GA for AWS App Runner in India, Mumbai Region (ap-south-1)

**Describe alternatives you've considered**

Still thinking of Elastic BeanStalk or ECS or Lightsail Containers for now.

**Additional context**
Anything else we should know?

Low Latency is highly important, hence looking for only Mumbai (ap-south-1) region and not for other regions.
Cost-Effective (Idle / Pause) and Less Maintainance (Fully Managed) are also important and hence App Runner suits us best.

**Comment by jsheld** [comment]
We are working on this and should have an update shortly. Thank you for your feedback.

**Comment by MinByeongDon** [comment]
I would like to see App Runner also supported in the Seoul region(ap-northeast-2). #131

**Comment by jwoodlee** [comment]
App Runner fans - not sure if you caught this App Runner launched in ap-south-1 in  but https://docs.aws.amazon.com/apprunner/latest/relnotes/release-2023-11-08-new-regions.html

We are looking to speak to people who are passionate about App Runner in the new regions.
