### ISSUE TITLE
Support for af-south-1 Africa (Cape Town)

### ISSUE THREAD

**Issue by bjorntheart** [aws/apprunner-roadmap#134]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like to use App Runner in the af-south-1 Africa (Cape Town).

**Describe alternatives you've considered**
I Considered using the eu-west-1 (Ireland) region with the lowest latency to Cape Town, but I want to avoid inter-region costs and desired much lower latency.

**Comment by igitur** [comment]
@bjorntheart This is still an issue, right? Why did you close the ticket?

**Comment by igitur** [comment]
New ticket logged at https://github.com/aws/apprunner-roadmap/issues/279 - Please, all, upvote there.
