### ISSUE TITLE
Integration with AWS Pricing Calculator

### ISSUE THREAD

**Issue by bfrancom** [aws/apprunner-roadmap#136]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Integration with AWS [Pricing Calculator](https://calculator.aws/).

**Describe alternatives you've considered**

The main App Runner Pricing [page](https://aws.amazon.com/apprunner/pricing/) has details, but when fully scoping out a cost estimate in the Pricing Calculator, App Runner is unavailable as an option.

**Additional context**
Anything else we should know?

Negatory good buddy.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by guikcd** [comment]
Since 2022/11/29, the service is now included in the calculator: https://calculator.aws/#/addService/apprunner
