### ISSUE TITLE
Run Jobs: a container that runs to complete a specific task and doesn't necessarily serve HTTP requests

### ISSUE THREAD

**Issue by adilnaimi** [aws/apprunner-roadmap#140]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Jobs: a container that runs to complete a specific task and doesn't necessarily serve HTTP requests, for example, background tasks, cron, scheduled tasks, etc.

**Describe alternatives you've considered**
I'm not aware of any easy alternative. AWS batch, for example, seems complicated and requires a learning curve if, for example, I want a task to run Celery background jobs without too much thinking of the Cloud configuration I have to make. 

**Additional context**
I have a Django API that serves HTTP requests, which fits perfectly in App runner. But at the same time, I want to Run the Celery task using App runner and only pay when Celery is executing a task.

**Comment by shaunakv1** [comment]
Related to https://github.com/aws/apprunner-roadmap/issues/96

**Comment by adilnaimi** [comment]
Already requested in https://github.com/aws/apprunner-roadmap/issues/96
