### ISSUE TITLE
Changing environment variables in AppRunner Console overrides HTTP healthcheck config

### ISSUE THREAD

**Issue by VladStarr** [aws/apprunner-roadmap#143]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Our services are running on App Runner without issues. We use HTTP service endpoint for health check configuration.
But as soon as AppRunner Console does not provide functionality to configure HTTP health checks, changing environment variables in Console leads to overriding health check configuration with TCP method and the service always rolls back.

**Describe alternatives you've considered**

For now changing environment variables can only be done through AWS CLI or any IaC tool (Terraform in our case).

**Additional context**

**Attachments**

Logs of service when changing environment variables via App Runner Console:

```
  | 2022-07-04T15:05:45.318+03:00 | [AppRunner] Service status is set to RUNNING.
  | 2022-07-04T15:08:52.998+03:00 | [AppRunner] Service update started.
  | 2022-07-04T15:08:53.496+03:00 | [AppRunner] Service status is set to OPERATION_IN_PROGRESS.
  | 2022-07-04T15:12:14.011+03:00 | [AppRunner] Successfully pulled image from ECR.
  | 2022-07-04T15:12:14.862+03:00 | [AppRunner] Provisioning instances and deploying image.
  | 2022-07-04T15:12:16.756+03:00 | [AppRunner] Performing health check on port '3000'.
  | 2022-07-04T15:18:37.093+03:00 | [AppRunner] Service update failed. For details, see service logs.
  | 2022-07-04T15:18:37.531+03:00 | [AppRunner] Service status is set to RUNNING.
  | 2022-07-04T15:29:57.792+03:00 | [AppRunner] Service update started.
  | 2022-07-04T15:29:58.280+03:00 | [AppRunner] Service status is set to OPERATION_IN_PROGRESS.
  | 2022-07-04T15:30:03.521+03:00 | [AppRunner] Provisioning instances and deploying image.
  | 2022-07-04T15:30:06.229+03:00 | [AppRunner] Performing health check on path '/health' and port '3000'.
  | 2022-07-04T15:31:37.368+03:00 | [AppRunner] Health check is successful. Routing traffic to application.
  | 2022-07-04T15:32:53.356+03:00 | [AppRunner] Successfully routed incoming traffic to application.
  | 2022-07-04T15:32:55.152+03:00 | [AppRunner] Service update completed successfully. New configuration is deployed.
  | 2022-07-04T15:32:56.040+03:00 | [AppRunner] Service status is set to RUNNING.
```

**Comment by pixnbit** [comment]
Very annoying

**Comment by snnles** [comment]
Hello everyone, Now you can configure HTTP health checks from App Runner console. You can also update your service configuration without overriding health check configuration. Our documentation will be updated soon.

Thank you for your feedback!
