### ISSUE TITLE
Support for eu-west-2 (London)

### ISSUE THREAD

**Issue by pauldougan** [aws/apprunner-roadmap#145]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like to use App Runner in the eu-west-2 (London) region.

**Describe alternatives you've considered**
eu-west-1 (Ireland) could potentially be used for some workloads 

**Additional context**
There are some workloads in the UK public sector that will require hosting in the London region for reasons of data sovereignty and for that reason may not be able to use eu-west-1 (Ireland)

**Comment by MinByeongDon** [comment]
I would like to see App Runner also supported in the Seoul region(ap-northeast-2). #131

**Comment by snnles** [comment]
App Runner is now available in London region.

https://aws.amazon.com/about-aws/whats-new/2023/11/aws-app-runner-london-mumbai-paris-regions/
