### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by alblue** [aws/apprunner-roadmap#16]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
The apprunner.yml file has a supported python and nodejs image for running from source, but by providing a Java installation you should be able to run Java code easily as well. This would be of great benefit to developers who have a hard time rebuilding image's and who want to run in the latest security updates.

Java is supported very well with github actions - you can install Java 8/11/17 (the LTS versions) - so having this as an apprunner base image would be very useful.

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/apprunner/latest/relnotes/release-2022-02-22-java.html

**Comment by pprahlad** [comment]
https://aws.amazon.com/about-aws/whats-new/2022/02/aws-app-runner-adds-java-platform/
