### ISSUE TITLE
DNS certificate record name validation length

### ISSUE THREAD

**Issue by nickloganfarmer** [aws/apprunner-roadmap#165]
When validating a certificate, App Runner requires the creation of three different CNAME records for the domain. My DNS is Namecheap and I can properly add the first record however, I cannot add the second one because its length is 65 characters excluding the characters of my domain at the end. Namecheap's host name character limit is 60 characters so I am currently unable to add my custom domain to App Runner. I already communicated with Namecheap's support and they are not budging on changing the character limit. Is there any way that the second DNS record name's length can be truncated down to 60 characters to be compatible with Namecheap? I know that App Runner suggests using Route 53 however, I honestly don't feel as though I should have to change my DNS just for one CNAME record. I believe making the record name compatible would remove a lot of other people's headaches.

**Comment by csuna-chen** [comment]
Hi Sorry, we rely on AWS ACM to create the certificate and generate the certificate record for us,  return the record back to customer, so the length is not under our control. We cannot limit the actual certificate record length on App Runner side.
