### ISSUE TITLE
VPC connector issues

### ISSUE THREAD

**Issue by nerdeveloper** [aws/apprunner-roadmap#168]
I created an app with a VPC connector, and when I try to edit it to Public access, it does not work. I have made multiple apps with VPC connectors, and I could switch them back to public access, but I cannot anymore. 

For example, this is the ARN of the service: arn:aws:apprunner:us-west-2:863801874088:service/Network-Config-Test-2/706f55a1156d42db97912396ee0a91c9. I cannot switch this app Back to *Public Access*, and there is no error. it doesn't just change

**Comment by hariohmprasath** [comment]
Hi @nerdeveloper,
Thanks for reaching out. I took a look at this service seems like the service is already deleted and none of the update operation has failed. So I have a few questions related to this ticket:

* VPC connector is used for outbound traffic, in this case are you flipping the outbound traffic from `Custom VPC` to `Public access`? 
* Is this operation performed using AWS console or using AWS CLI?
* If this operation gets performed using AWS console, did you notice any error in the browser console? This can be checked by opening up browser developer console.

Let us know your response whenever you have some time. Thanks.

**Comment by nerdeveloper** [comment]
Someone on my team will reply this thread.

**Comment by majorchork** [comment]
hello @hariohmprasath 

The service was accidentally deleted but here's the arn for another service with a similar bug` arn:aws:apprunner:us-west-2:863801874088:service/config-test-3/a84fb15a494f43eba6d96e8454bd35cb.`
- yes I am flipping from `Custom VPC to Public access`
- so the operation is performed both on the aws console and via API call.
- The update operation is successful, no errors, but when I switch from Custom vpc to Public access, I still see the custom vpc details on the service.

**Comment by majorchork** [comment]
this is another service before and after switching <img width="1440" alt="Screenshot 2023-02-10 at 10 39 16" src="https://user-images.githubusercontent.com/69452689/218057692-5520d353-acd7-4672-8ae0-45833d843543.png"> 
<img width="966" alt="Screenshot 2023-02-10 at 10 43 51" src="https://user-images.githubusercontent.com/69452689/218058683-407757e3-01e5-4adf-9b89-5494e91df5e7.png">

**Comment by hariohmprasath** [comment]
Hi @majorchork, 
Thanks for sharing the details. I was able to recreate this and confirm its a bug on our console side. Even though service gets successfully updated to `Public Access` for all Outbound traffic, the console section is not fully updated which is creating a confusion here. 

I understand this is a bit of inconvenience, but this shouldn't block you from using the service as you can look at the `Outgoing network traffic` field (highlight below)  for current state 
![Screenshot 2023-02-10 at 10 58 24 AM](https://user-images.githubusercontent.com/2615325/218178866-e5f919c2-18c5-47b8-b323-d80b42d028bd.png)

We will prioritize the fix internally and keep you posted regarding the progress. Thanks for reaching out.

**Comment by majorchork** [comment]
Hello @hariohmprasath,

Thanks for taking a look, I'll move forward as recommended.
I look forward to hearing from you about the fix.

Best Regards.
