### ISSUE TITLE
Add support for .NET 7 (dotnet7)

### ISSUE THREAD

**Issue by goenning** [aws/apprunner-roadmap#179]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Upgrade an app from dotnet6 to dotnet7

**Describe alternatives you've considered**

Staying on dotnet6 🫠

**Additional context**

dotnet7 is faster and has been around for a while, would be great to have it on apprunner too!

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by nc-master** [comment]
AWS Is making hard our decision of staying here while working with dotnet.

**Comment by jsheld** [comment]
At this time, we are not adding support for .NET 7 as we are only targeting .NET LTS releases. Unfortunately, .NET 7 is a STS release. As suggested by @andreas-bergstrom, a Docker image with what you need published to ECR would probably be the easiest route for what you want. By the way, you can find .NET support policy information here: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core. Hope this helps.
