### ISSUE TITLE
Support for AWS Secret Manager

### ISSUE THREAD

**Issue by adilnaimi** [aws/apprunner-roadmap#19]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments; they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Tell us about your request**
Currently, App Runner supports environment variables; it works but is not secure enough to configure credentials, Database passwords, and usernames.
Adding support for the AWS secret manager will help to access credentials from a safe location.

**Comment by dreamorosi** [comment]
Duplicate of #6

**Comment by jvisker** [comment]
@adilnaimi Did something actually ship on this? Or was this closed as a duplicate?

**Comment by adilnaimi** [comment]
@jvisker sorry for my late reply. I'm reopening this issue as I closed it by mistake

**Comment by adilnaimi** [comment]
Duplicate of https://github.com/aws/apprunner-roadmap/issues/6

**Comment by rhbecker** [comment]
@adilnaimi: Given this was closed as a duplicate of an issue with a roadmap status of "We are working on it", I suspect it should not have a roadmap status of "Just Shipped".
