### ISSUE TITLE
AWS Console - Persist Application Logs timeframe filter and fix order of log lines

### ISSUE THREAD

**Issue by joelbarnard** [aws/apprunner-roadmap#190]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Update the AWS Console to persist the timeframe selected when viewing Application Logs. Currently it defaults to "Last 1 Day", however for my application this makes no sense....I continuously have to select "5 minutes".

Also, the ordering of events in the Application Log is wrong (lines with same timestamp are random)...CloudWatch logs shows them in the correct order.

**Describe alternatives you've considered**

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by jsheld** [comment]
The console does not modify the ordering of events from CloudWatch so multiple events with the same timestamp should be shown in the same order in the console that CW shows them. We did make a change here to display events from oldest to newest but apart from that, all logic remains the same as it was. If this issue persists, please feel free to reopen it.
