### ISSUE TITLE
HTTP to HTTPS redirect not working in PHP runtime

### ISSUE THREAD

**Issue by cade-coreschedule** [aws/apprunner-roadmap#194]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
HTTP to HTTPS redirect with the PHP runtime. HTTP browser or curl request to the App Runner generated URL times out. HTTP request to a custom domain name linked and pointed to the App Runner service times out. HTTPS requests are handled fine.

**Describe alternatives you've considered**
No alternative.

**Additional context**
Anything else we should know?
Brand new App Runner service using the PHP 8.1 runtime. HTTP requests timeout and are never redirected to HTTPS.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by msumithr** [comment]
Hello,
Thank you for reaching out. Could you share the App runner service arn?

**Comment by msumithr** [comment]
Hello @cade-coreschedule 
Thank you for reaching out! We identified an issue with the http->https redirect routing configuration, which we have fixed. Could you please retry again? Please let us know if you see further issues.

**Comment by msumithr** [comment]
Hi @cade-coreschedule , the fix was not related to the underlying runtime. New services (regardless of the platform) should see http->https redirect working.
