### ISSUE TITLE
App Runner does not seem to send all HTTP response headers

### ISSUE THREAD

**Issue by Offlein** [aws/apprunner-roadmap#211]
It's not clear if this is a missing feature issue; a question of documentation; or somehow an idiosyncrasy of our own system, but custom HTTP response headers do not seem to be included once our application is deployed to App Runner (via AWS Copilot).

We have a custom header ("x-app-version") on all XHR responses to our backend that conveys the expected version of the application, for the purposes of ensuring the frontend application doesn't need to be refreshed.

This does not seem to return, and my guess is that it's filtered out somewhere along in the orchestration process, but it's not clear, if so, where that happens.

**Comment by Offlein** [comment]
@msumithr Thank you -- yes. Our application's test environment ARN is `arn:aws:apprunner:us-west-2:021743263840:service/tim-test-backend/416c324669af48aca3d5a47426b9b032` 

I was on with a support person as well, who couldn't determine an answer to this and said he'd be elevating my question, but advised me to possibly leave a message here too.

**Comment by dhavaln** [comment]
@Offlein were you able to receive any updates?

**Comment by Offlein** [comment]
Hi @dhavaln. Thanks for following up. The AWS support personnel never actually heard back from the internal personnel and we closed the ticket. At some point I noticed the thing was now sending the headers we were missing. I don't believe we changed anything -- not sure if something changed on AppRunner's side? But it may indeed be our own issue. I'm not sure.

Either way, the problem no longer exists for us. I'm not sure what we can all learn from this, but, uh. "Don't do it again" I guess? I'm not sure what I did, but that'll be the advice I give myself.

**Comment by marco910** [comment]
Hi there,

I'm running a Next.js app using App Runner and try to set some custom HTTP response header. My application settings seem to be correct, but the headers are not visible in the App Runner response. 

Do you have any ideas how I can fix this and make App Runner return also my custom HTTP headers?
