### ISSUE TITLE
Provide AppRunner in Paris region (eu-west-3)

### ISSUE THREAD

**Issue by tch-at-bain** [aws/apprunner-roadmap#221]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Provide AppRunner in Paris Region (eu-west-3)

**Describe alternatives you've considered**
Running AppRunner in supported region and running data services in another one but that incurs inter-region data transfer costs and complicates setup.

**Additional context**
Critical to some of our business cases.

**Attachments**
NA

**Comment by shentonfreude** [comment]
I'm running AppRunner in Paris now; I didn't now I couldn't :-)
![Screenshot 2024-02-28 at 10 10 12](https://github.com/aws/apprunner-roadmap/assets/68655/cbcf4464-46b6-4cda-8e2d-3e1824f6bc4b)

**Comment by backnol-aws** [comment]
App Runner launched in eu-west-3
https://aws.amazon.com/about-aws/whats-new/2023/11/aws-app-runner-london-mumbai-paris-regions/
