### ISSUE TITLE
More than 4GB of memory

### ISSUE THREAD

**Issue by umireon** [aws/apprunner-roadmap#24]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
It would be great if more than 4GB of memory, preferably 16GB, can be provided. With this amount of memory, we can handle all kinds of files which any browser can upload.

**Describe alternatives you've considered**
We consider using Fargate because it can provide 30GB of memory or using S3 Presigned URL to let S3 handle such large files.

**Comment by dmacbride-ep** [comment]
Our solution would also require more memory be allocated to some containers. Our containerized java apps, which run in tomcat, almost always require 8+GB or native memory to support 6GB java heap.

**Comment by itizarsa** [comment]
We also are in need of high memory & CPU

**Comment by snnles** [comment]
Hello everyone, App Runner now supports higher compute configurations with up-to 4 vCPU and 12 GB compute memory.

Launch announcement: https://aws.amazon.com/about-aws/whats-new/2023/04/aws-app-runner-compute-configurations/
