### ISSUE TITLE
Lower CPU & memory configs

### ISSUE THREAD

**Issue by andreas-bergstrom** [aws/apprunner-roadmap#25]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
While Python and other multi-threaded runtimes can utilize 2GB to its full extent, Node (being CPU-bound due to its single threading) really can't unless you do heavy in-process caching. A normal Node-process will rarely use more than 100mb. This means Node-services on App Runner will be really expensive to scale horizontally, just like on Fargate.

**Describe alternatives you've considered**
512MB or at least 1GB memory options with a slightly lower price.

**Comment by mwarkentin** [comment]
Looking at the pricing page I initially calculated minimum monthly cost at $5 per month. Since it's measured in Gb-month I assumed 1Gb would be an option, only later noticed that 2Gb was minimum ($10/m).

**Comment by snnles** [comment]
Hello everyone,

What compute configs (CPU and memory) would you like to see in App Runner? It will be greatly helpful if you can share the use cases that you want to run on lower compute configurations? For example, will you use lower compute config to run applications in development/test environments, or applications that are built on specific language or framework.

Thank you all for your feedback in advance!

**Comment by MarcoGlauser** [comment]
One usage example for us is a simple nginx reverse proxy that sips resources compared to our web services. For our peak load, 0.5 cpu and 512 MB would be more than enough, since we can always scale horizontally if needed. 

Our python backend uses 512MB on average, so 1GB would be nice on that front as well.

Our node backend uses 200MB on average, so 512MB would be nice. 

Since both python and node are mostly single core optimized, we're happy with just 1 cpu.

**Comment by jvisker** [comment]
For development environments being able to have as small of option as possible would be great. For many development purposes .25 vCPU is plenty to test out the functionality of an application.

**Comment by snnles** [comment]
Hello everyone, App Runner now supports lower compute configurations with 0.25 vCPU and 0.5 vCPU. Thank you for your feedback.

Launch announcement: https://aws.amazon.com/about-aws/whats-new/2023/04/aws-app-runner-compute-configurations/
