### ISSUE TITLE
What is the status of the roadmap?

### ISSUE THREAD

**Issue by rshekhtm** [aws/apprunner-roadmap#250]
I noticed that the project containing the roadmap was recently closed - what does that mean? Is the roadmap no longer public? Is App Runner development still happening?

Tagging @backnol-aws since you were the one to close it.

**Comment by chai3** [comment]
I think AWS Beanstalk development has ended and is in maintenance mode.

https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/relnotes.html
![image](https://github.com/aws/apprunner-roadmap/assets/16031581/5aa3c248-c39f-4f44-b162-75d65043126e)

@backnol-aws Is AppRunner in maintenance mode like Beanstalk?

**Comment by tom-carbontrail** [comment]
Seems the project is open again. https://github.com/aws/apprunner-roadmap/projects/1

Phew!

**Comment by backnol-aws** [comment]
Hey folks - Sorry about the churn, we tried to update the GitHub project. The old version of GitHub Projects is going EOL in August. We’ve migrated to the new version and will be trying to scrub the Roadmap project for accuracy in the coming weeks.

**Comment by wesmontgomery** [comment]
@backnol-aws it has been about a month since you posted your last comment, yet nothing has changed or shipped. Is this project effectively dead?

I seems like the whole containers team at AWS has been reassigned to work on Gen AI, yet here we are as customers begging to pay you for features we want.

**Comment by neidiom** [comment]
There is some movement.

* https://docs.aws.amazon.com/apprunner/latest/relnotes/release-2024-11-18-2024-infra-updates.html

```
App Runner networking and compute infrastructure updates on November 18, 2024

```
