### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by spesnova** [aws/apprunner-roadmap#27]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Supporting Ruby 3.0 and 2.7 for [the managed runtimes](https://docs.aws.amazon.com/apprunner/latest/dg/service-source-code.html#service-source-code.managed-runtimes). 
As of today(May 19, 2021), App Runner only supports Python 3.x and Node.js 12.x for [the managed runtimes](https://docs.aws.amazon.com/apprunner/latest/dg/service-source-code.html#service-source-code.managed-runtimes). 

**Describe alternatives you've considered**

- Buildpack support (https://github.com/aws/apprunner-roadmap/issues/11)
- Creating [image-based App Runner service](https://docs.aws.amazon.com/apprunner/latest/dg/service-source-image.html) with own Docker images for Ruby

**Comment by snnles** [comment]
App Runner now supports Ruby managed runtime.

https://aws.amazon.com/about-aws/whats-new/2022/10/aws-app-runner-support-php-go-dot-net-ruby-managed-runtimes/
