### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by kimyan** [aws/apprunner-roadmap#31]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Supporting PHP 7 and 8 for the managed runtimes. As of today(May 21, 2021), App Runner only supports Python 3.x and Node.js 12.x for the managed runtimes. We have many PHP assets like apps using Laravel, CakePHP, and so on. I believe that all PHP lovers can't wait to support PHP as managed runtime in App Runner.

**Describe alternatives you've considered**
- Buildpack support (#11)
- Creating image-based App Runner service with own Docker images for PHP

**Comment by jewelhuq** [comment]
any update?

**Comment by snnles** [comment]
App Runner now supports PHP managed runtime.

https://aws.amazon.com/about-aws/whats-new/2022/10/aws-app-runner-support-php-go-dot-net-ruby-managed-runtimes/
