### ISSUE TITLE
Unable to find apprunner resource on aws cli v2.2.5

### ISSUE THREAD

**Issue by srikanth-ve** [aws/apprunner-roadmap#34]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Tried using aws cli latest version (upgraded to aws-cli/2.2.5 Python/3.8.8 Darwin/19.4.0 exe/x86_64 prompt/off), on MacOS, but do not find any resource with the name apprunner as specified in the api documentation [here](https://docs.aws.amazon.com/apprunner/latest/api/API_CreateConnection.html)

I have also ensured that i have selected us-east-1 as the region mentioned [here](https://docs.aws.amazon.com/general/latest/gr/apprunner.html) 

**Describe alternatives you've considered**
I tried with other regions mentioned in the service endpoints table of the "AWS App Runner endpoints and quotas"

**Additional context**
None

**Attachments**
<img width="1237" alt="aws-app-runner-issue-1a" src="https://user-images.githubusercontent.com/80290004/119212955-6fb90c80-bad9-11eb-824b-944def46be07.png">

**Comment by toricls** [comment]
@srikanth-ve Sorry for the inconvenience 🙏

AWS CLI v2 with App Runner support is coming very soon, and we'll let you know here once it's out!

(If you need immediate access try the latest AWS CLI v1 which already has support for App Runner)

**Comment by toricls** [comment]
AWS CLI v2.2.6 with App Runner support is now live!

- GitHub Release: https://github.com/aws/aws-cli/releases/tag/2.2.6
- How to update: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html

**Comment by pprahlad** [comment]
Closing now that AWS CLI v2 is live.
