### ISSUE TITLE
Support for Node.js 14

### ISSUE THREAD

**Issue by CalogeroMandracchia** [aws/apprunner-roadmap#36]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
It would be great to have support for at least nodejs 14, since it is the LTS version and nodejs 12 is in maintenance status.
Nodejs 16 would be great too!

**Comment by baer** [comment]
At the time of this writing, Node support is as follows:

- Current: v16
- Active LTS: v14
- Maintenance Only: v12

Below is the support schedule for reference.

![image](https://user-images.githubusercontent.com/940667/120043849-95ef1880-bfc1-11eb-84a9-22b429a15e25.png)

https://nodejs.org/en/about/releases/

**Comment by mwarkentin** [comment]
Linking to https://github.com/aws/apprunner-roadmap/issues/11 as that could be another way this would be provided.
