### ISSUE TITLE
Build failes due to Apprunner failing to pull private github repository

### ISSUE THREAD

**Issue by s-kris** [aws/apprunner-roadmap#38]
Hello,

I'm trying to deploy a nodejs app to apprunner using my github account. 
A successful GitHub connection is made (was able to list all repositories and select the required one), but the build fails with the error: `Failed to pull repository xxxxxx`. Tried to deploy a public repository, it's done successfully. 
Your customer care exec says that `handshake is not completed` but in the github connections page, the 'Complete Handshake' button is not active.

Waiting for a fix.
Thank you!

p.s
I already spoke to your customer care. Just opening an issue here for more [visibility](https://twitter.com/AWSSupport/status/1398995435168186370).

**Comment by s-kris** [comment]
I ran some tests, I think I identified the issue.
Let me clear few things first.
1. The Github app installation is valid.
2. The Github app has access.
3. The repository and branch exist.

Reason for failure:
If . (dot) is present in the repo's name then the AppRunner service fails to pull it.

**Comment by 1tonyca** [comment]
This has been fixed, thanks
