### ISSUE TITLE
Support for ap-southeast-2

### ISSUE THREAD

**Issue by forkfork** [aws/apprunner-roadmap#41]
**Tell us about your request**
I would love to have access to this service in ap-southeast-2 (Sydney)

**Describe alternatives you've considered**
Oregon, but latency is a little high.

**Additional context**
While in our 4th lockdown in Melbourne I have a sudden craving for low latency responses to my App Runner service.

**Comment by snnles** [comment]
Hello everyone, App Runner is now available in ap-southeast-2 (Sydney) region. Please try out App Runner and let us know of any feedback that you may have. Thank you for all your feedback and support.

Launch Announcement - https://aws.amazon.com/about-aws/whats-new/2023/03/aws-app-runner-singapore-frankfurt-sydney-regions/
