### ISSUE TITLE
Ability to have integration with AWS codecommit

### ISSUE THREAD

**Issue by nitishSa** [aws/apprunner-roadmap#44]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Adding AWS Codecommit support along with Github integration

**Describe alternatives you've considered**
Can't migrate code to Github. Would love to have codecommit integration

**Comment by toricls** [comment]
Hello @nitishSa! Regarding CodeCommit support, we're tracking it in #3 along with other code/image repository services.

Although App Runner doesn't natively support CodeCommit today, you can actually integrate it with App Runner by using our AWS Copilot CLI, as I described in the issue https://github.com/aws/apprunner-roadmap/issues/3#issuecomment-851889565. Hope this would meet your needs as an interim/alternative solution.

**Comment by toricls** [comment]
Closing this issue since we already have #3 🙌
