### ISSUE TITLE
Interrupt service deployment + allow for config modification for a failed service

### ISSUE THREAD

**Issue by akshayram-wolverine** [aws/apprunner-roadmap#49]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We heard from customers that they would like to recover from errors faster. There are two use cases here:  

1. For an already deployed and running service: Customers would like to interrupt a service to recover from a bad config instead of waiting for the default rollback period. This would help improve productivity and help recover from any failures faster. 
2. For a new service: Customers should be able to modify the config of a service in the create failed state to recover back to a healthy and running state. This would help not having to duplicate the config for a new service creation and instead just fix the specific problem in the failed service. 

**Describe alternatives you've considered**
Wait for the service rollback to complete in use case 1. 
Use the create failed service as read only to debug but customers need to recreate a new service

**Comment by Mugane** [comment]
This is ESSENTIAL. I cannot emphasize how grossly inconvenient it is to have to enter DOZENS OF ENVIRONMENT VARIABLES OVER AND OVER AGAIN because of some random error that causes new deploys to fail leaving starting from SCRATCH as the only option.

**Comment by akshayram-wolverine** [comment]
I know its this does not directly solve your use case but you can now edit environment variables in the console for a service that is created and running. To directly address your issue, we will work on allowing updates to a failed service and post on this thread as we have more to share.

**Comment by Mugane** [comment]
By console you mean via AWS CLI or is there a way to get shell access to a container?

**Comment by RemiKalbe** [comment]
How has this fundamental feature remained unaddressed after more than a year?

**Comment by lucashfreitas** [comment]
It's insane that we have to completely remove an APP because a Create failed. I was deploying a JSON server just to test app runner and after a failed deployment I will have to delete and recreate the app from scratch.

**Comment by sefasenturk95** [comment]
And update on this!?

**Comment by Raptor2277** [comment]
It completely baffles my mind that this is still hasn't been addressed. Do you really expect us to destroy and recreate the resource if it fails?

**Comment by AmmarBashir** [comment]
When is this update going to come out?

**Comment by amitgupta85** [comment]
Thank you for your patience. We are looking at this feedback and we will keep you updated as we plan and make progress on this issue.

**Comment by jaminhaber** [comment]
I will implement this for AWS free of charge because it would probably take less time than working around it as the end-user

**Comment by jethronap** [comment]
Please do them a favour and implement this for free. I've spent the well part of a weekend and still cannot deploy due to this health-check failure...

**Comment by AnthonyMichaelTDM** [comment]
I too would find this immensely helpful

**Comment by yaronlevi** [comment]
Any updates on this?
Still trying to wrap my head around how this was left out.
Thank you for any help on the issue.
If you can shed some light and rough ETA on this.

**Comment by sefasenturk95** [comment]
Any updates on this one?

**Comment by msumithr** [comment]
Hello all,
Thank you the feedback. App runner is actively working on this feature and we will post our updates soon.

**Comment by snnles** [comment]
App Runner now support update and rebuild of a service in failed state. See launch announcement for more details:
https://aws.amazon.com/about-aws/whats-new/2023/06/aws-app-runner-update-rebuild-failed-service/

**Comment by hd-o** [comment]
@snnles Is there any ongoing work on interrupting an in-progress deployment? (like EB's [abort-environment-update](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticbeanstalk/abort-environment-update.html))

**Comment by ascopes** [comment]
@snnles any update on the second part of this ticket? I've been waiting nearly 30 minutes now for this to enter a failed state... it will keep trying but it will never succeed without me cancelling it, but there is no ability to do that.
