### ISSUE TITLE
Ability to connect to ElastiCache Instances

### ISSUE THREAD

**Issue by selected-pixel-jameson** [aws/apprunner-roadmap#51]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Need the ability to connect to ElastiCache Instances.

**Comment by toricls** [comment]
Thank you @selected-pixel-jameson for creating this issue! I'm closing this issue because #1 will perfectly address your needs!
