### ISSUE TITLE
Enable to register App Runner service domain as an alias record in Route 53.

### ISSUE THREAD

**Issue by a2ush** [aws/apprunner-roadmap#53]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Request to register App Runner service default domain as an alias record, as well as Elastic Beanstalk.

Currently, we have to register the service domain as CNAME record. 
So we cannot associate it with a zone apex in Route 53.

**Additional context**

Choosing between alias and non-alias records
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html

**Comment by rsikandar** [comment]
Please address this issue, its insane to sell the Apprunner service on your platform and not be able to target it via root domain. How was this even allowed to be pushed to the customer without this feature, it's 2022 now.

**Comment by kevlened** [comment]
[The App Runner documentation](https://docs.aws.amazon.com/en_us/apprunner/latest/dg/manage-custom-domains.html) implies this feature already exists. It says:

    You can specify a domain to associate with your App Runner service in the following ways:

    * A root domain – For example, example.com. You can optionally associate www.example.com too as part of the same operation.

It also states:

    The following example shows how you can use multiple custom domain associations:

    1. Associate example.com with the home page of your service. Enable the www to also associate www.example.com.

If it's possible to associate a root domain with App Runner as mentioned above, an example would likely resolve this issue for most people.

**Comment by keerataws** [comment]
Thank you for bringing this up. Looking into it.

**Comment by zw627** [comment]
This the reply we got from AWS Support:

> Similar asks has been requested by multiple AWS customer on Github hub page[1] and the service team has already taken this up as a feature request which is currently been worked upon by our internal team on high priority, however we do not have an ETA for the same.
>
> [1] Github: https://github.com/aws/apprunner-roadmap/issues/53

In our case, we have decided not to use Route 53 to manage our root domain for now and added the CNAME records required by App Runner directly to our internal DNS instead.

**Comment by tforbus** [comment]
> @tforbus Just a heads up, S3 can't terminate tls, so in your current configuration, `http://example.com` would redirect, but `https://example.com` would have a cert issue. You need to point your DNS to a CloudFront distribution that serves from your S3 bucket. You'll also need to configure your distribution to terminate tls using a cert created in ACM.
> 
> Which is to say, there's quite a bit of infra required for something the docs suggest should work out of the box.

Thanks, I had noticed the redirect issues. Had looked at doing CloudFront like you suggested but was having issues with it pointing to the bucket. I'd assumed from the redirect rules, but maybe the cert like you're talking about.

**Comment by tcldr** [comment]
This pairs with https://github.com/aws/aws-cdk/issues/19740

**Comment by marekaf** [comment]
Hi. It seems like this is still the issue. 
Would it be possible to at least modify the docs to clearly state this is not possible to do? The docs are misleading now.

**Comment by Negan1911** [comment]
Cloudfront is not ideal, and adds ~300ms of latency that doesn't happen when hitting the root apprunner URL.

And yes, this is still an issue

**Comment by keerataws** [comment]
Hi, working on the docs to remove the misleading information.

**Comment by keerataws** [comment]
@[marekaf](https://github.com/marekaf) the document has been updated with a Note to clarify that this is not supported at the moment with Route 53.

**Comment by snnles** [comment]
App Runner now supports Amazon Route 53 alias record for App Runner service domain name. Thank you all for the feedback.
https://docs.aws.amazon.com/apprunner/latest/relnotes/release-2022-08-30-route53.html

**Comment by mraszplewicz** [comment]
Hi,

I was able to create an alias using the AWS console, thank you!

I am trying to create an alias record using AWS API. How can I get AliasTarget.HostedZoneId for App Runner?

**Comment by scuw19** [comment]
Hi, here is the link to Apprunner hosted zone id: https://docs.aws.amazon.com/general/latest/gr/apprunner.html

**Comment by ernestyouniverse** [comment]
I'm using Terraform generally, but same thing in the end.

I create a redirection by a CNAME record to the App Runners exposed `.service_url`:

```
resource "aws_route53_record" "cname_app_runner" {
  zone_id = aws_route53_zone.main.zone_id
  name    = "www.subdomain-1.subdomainovich.my-domain.net"
  type    = "CNAME"
  ttl     = "300"
  records = [---apprunner_service_arn---]
}
```
in context:
```
resource "aws_route53_zone" "main" {
  name = "my-domain.net"
}

# NS Records to delegate DNS resolution to AWS Route 53 name servers
resource "aws_route53_record" "ns_records" {
  zone_id         = aws_route53_zone.main.zone_id
  name            = aws_route53_zone.main.name
  allow_overwrite = true
  type            = "NS"
  ttl             = 300
  records         = ["ns-smth.smth-smth.smth", "ns-smth.smth-smth.smth", "ns-smth.smth-smth.smth", "ns-smth.smth-smth.smth.smth"]
}

# CNAME Record for App Runner
resource "aws_route53_record" "cname_app_runner" {
  zone_id = aws_route53_zone.main.zone_id
  name    = "www.subdomain-1.subdomainovich.my-domain.net"
  type    = "CNAME"
  ttl     = "300"
  records = [---apprunner_service_arn---]
}

# Alias for Cloudfront
resource "aws_route53_record" "a_cloudfront" {
  zone_id = aws_route53_zone.main.zone_id
  name    = "www.subdomain.subdomainovich.my-domain.net"
  type    = "A"
  # create alias (required: name, zone_id)
  alias {
    name                   = aws_cloudfront_distribution.main.domain_name
    zone_id                = aws_cloudfront_distribution.main.hosted_zone_id
    evaluate_target_health = true
  }
}

```
