### ISSUE TITLE
Add button for creating DNS records in Route 53 when adding custom domain

### ISSUE THREAD

**Issue by vasimi** [aws/apprunner-roadmap#57]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add button that would automatically create DNS records in Route 53 when adding custom domain. This works on other AWS services, but missing in App Runner. :/

**Describe alternatives you've considered**
Creating dns records manually... meh

**Comment by csuna-chen** [comment]
Hi, Right now if you use Alias Record type, then there is a button to let you directly click App Runner domain.

**Comment by snnles** [comment]
App Runner now supports Amazon Route 53 Alias records for DNS. You can directly link your DNS to App Runner from Route 53.

Launch announcement: https://aws.amazon.com/about-aws/whats-new/2022/09/aws-app-runner-supports-amazon-route-53-alias-record-root-domain-name/

Developer Guide: https://docs.aws.amazon.com/apprunner/latest/dg/manage-custom-domains-route53.html
