### ISSUE TITLE
External Configuration/Secret Sources

### ISSUE THREAD

**Issue by RichiCoder1** [aws/apprunner-roadmap#6]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
The ability to plug in App Configuration and Secrets from an external source (AWS SSM Parameter Store and AWS Secret Manager as MVP). Essentially the equivalent of ECS/Kubernetes, where you can name a provider, some parameters, and the ability to provide values as either environment variables or files. 

**Describe alternatives you've considered**
Baking in config at build time and building multiple images.

**Additional context**
Good examples of great experiences today that should inspire (if not straight up use):
* Kubernetes ConfigMap and [Secret CSI](https://github.com/kubernetes-sigs/secrets-store-csi-driver)
* ECS Functionality (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-parameters.html)

It'd be nice to also be able to eventually use Vault transparently, but that might be a strech.

**Comment by hatskier** [comment]
Hey @RichiCoder1 , do you know the estimated date of this feature? I would love to use AWS App Runner, but can't find a secure way to pass secrets (e.g. DB credentials) to the App Runner instances

**Comment by RichiCoder1** [comment]
> Hey @RichiCoder1 , do you know the estimated date of this feature? I would love to use AWS App Runner, but can't find a secure way to pass secrets (e.g. DB credentials) to the App Runner instances

I'm afraid I'm not affiliated with AWS at all, so I have about as much of an answer as you do 😅. However, the ticket is marked as `We are working on it`, and it at least partially references a feature that already exists with the underlying engine (ECS) so I'm hoping personally it'll land sometime this FY.

**Comment by atali** [comment]
Hi,
any news about that feature? It's really blocking our team to use AppRunner.
I am expecting something similar to ECS:

ecs.Secret.fromSecretsManager(secret, field?)
Please keep us updated.
In the meanwhile do you have any workaround?
Thx

**Comment by hariohmprasath** [comment]
Hi @atali,
Thanks for reaching out. The team is actively working on this feature, we will keep you updated about the progress in the upcoming weeks.

**Comment by adonig** [comment]
@atali Not sure whether this is a working workaround because I didn't try it, but isn't it possible to pass the secret ARN as an environment variable to the container and there use the awscli to get the secret value and do something with it, for example put it in the container command execution environment in docker-entrypoint.sh like this:

```bash
#!/bin/bash
set -euxo pipefail
MY_SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $MY_SECRET_ARN --query SecretString --output text)
exec env MY_VARIABLE=MY_SECRET_VALUE "$@"
```

I believe it should work as long as you have a VPC connector to a VPC with a Secrets Manager VPC endpoint and your task role allows the containers to access Secrets Manager.

**Comment by atali** [comment]
Thank you @adonig , I will give a try. Hopefully the new feature will be available soon.
Keep the good work !

**Comment by jvisker** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/01/aws-app-runner-secrets-configuration-aws-secrets-systems-manager/

**Comment by kichik** [comment]
Thank you! CDK support now pretty please :)

**Comment by snnles** [comment]
This feature is now supported in App Runner. Please visit the What's New announcement that also has links to a deep dive blogpost and developer guide. Thank you all for your feedback and support.

https://aws.amazon.com/about-aws/whats-new/2023/01/aws-app-runner-secrets-configuration-aws-secrets-systems-manager/

**Comment by hariohmprasath** [comment]
> Thank you! CDK support now pretty please :)

Yes, the team will work on it next and we will keep you posted on the updates.

**Comment by atali** [comment]
Will the CDK L1 construct support it in the short time because it's automatically generated ?

**Comment by hariohmprasath** [comment]
Hi @atali,
Yes, since we have added support for CFN, L1 constructs should be available in the upcoming release of `aws-cdk`, please watch out https://github.com/aws/aws-cdk repo for upcoming releases and change logs. Thanks

**Comment by atali** [comment]
My secret is a json and I was expecting to select a field into that json, any way you can support that ?


I was expecting to do like ecs:

```
const loadBalancedFargateService = new ApplicationLoadBalancedFargateService(stack, 'Service', {
  cluster,
  memoryLimitMiB: 1024,
  cpu: 512,
  taskImageOptions: {
    image: ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
    secrets: {
      // Assign a JSON value from the secret to a environment variable
      MYSQL_HOST: Secret.fromSecretsManager(cluster.secret!, 'host'),
      MYSQL_PORT: Secret.fromSecretsManager(cluster.secret!, 'port'),
      MYSQL_USER: Secret.fromSecretsManager(cluster.secret!, 'username'),
      MYSQL_PASSWORD: Secret.fromSecretsManager(cluster.secret!, 'password'),
      MYSQL_DATABASE: Secret.fromSecretsManager(cluster.secret!, 'dbname'),
    }
  },
});
```

**Comment by hariohmprasath** [comment]
Hi @kichik,
PR for the CDK integration is merged now, so you should be all set :) - https://github.com/aws/aws-cdk/pull/23692

Here are some usage patterns:

```
environmentSecrets: {
  SECRET: apprunner.Secret.fromSecretsManager(secret),
  PARAMETER: apprunner.Secret.fromSsmParameter(parameter),
  SECRET_ID: apprunner.Secret.fromSecretsManagerVersion(secret, { versionId: 'version-id' }),
  SECRET_STAGE: apprunner.Secret.fromSecretsManagerVersion(secret, { versionStage: 'version-stage' }),
},
```

Here are the service methods that you can use to directly add this integration:

```
...
service.addSecret('LATER_SECRET', apprunner.Secret.fromSecretsManager(secret, 'field'));
service.addEnvironmentVariable('SECOND_ENVIRONEMENT_VARIABLE', 'second test value');
...

Let me know if you have any questions. Thanks

**Comment by vimalprasathr** [comment]
Can we update bulk secret value in apprunner

**Comment by msumithr** [comment]
Yes, once Customer updates all the secrets via AWS Secrets Manager and then trigger a single deployment on App Runner, we will be refreshing all the secrets.

**Comment by BuraChuhadar** [comment]
Hello,

I am also curious do you have an example code where it shows to add ssm parameter arn with source "SSM Parameter Store" as an environment variable under AWS CDK?

**Comment by moltar** [comment]
> Yes, once Customer updates all the secrets via AWS Secrets Manager and then trigger a single deployment on App Runner, we will be refreshing all the secrets.

Is there a way to trigger auto-reload upon secret updates via CDK?

Perhaps we could watch for an event, and then somehow call an API to force-reload?

**Comment by hariohmprasath** [comment]
Hi @moltar, You can listen to the AWS Eventbridge events and invoke `aws apprunner start-deployment` API  to force a new deployment

**Comment by moltar** [comment]
> Hi @moltar, You can listen to the AWS Eventbridge events and invoke `aws apprunner start-deployment` API to force a new deployment

Hey, yeah, tried that. But EB events only fire if there is CloudTrail on the account, which is a whole other can of worms 😁

**Comment by sefasenturk95** [comment]
@moltar How did you end up fixing this, I have this issue now as well, looking for a way on how to fix it..
