### ISSUE TITLE
.NET 6 as a supported runtime from a source code repository

### ISSUE THREAD

**Issue by ueberhund** [aws/apprunner-roadmap#60]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Describe alternatives you've considered**

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by sitepodmatt** [comment]
.Net is not an LTS. You might as well focus on 6.0 at this point given its shortly to be in RC and RTM later this year.

**Comment by poloboc** [comment]
+1 for .net6

**Comment by snnles** [comment]
App Runner now supports .net to run applications from source code.

https://aws.amazon.com/about-aws/whats-new/2022/10/aws-app-runner-support-php-go-dot-net-ruby-managed-runtimes/
