### ISSUE TITLE
Failure to Create App Runner Service using Bitnami Drupal Docker from ECR

### ISSUE THREAD

**Issue by amgci** [aws/apprunner-roadmap#62]
Have tried twice to create an App Runner service using the Bitnami Drupal Container from ECR (public.ecr.aws/bitnami/drupal:latest)

Continues to fail

Log - provides no information on reason - contains only:

06-24-2021 10:14 AM [AppRunner] Service status is set to OPERATION_IN_PROGRESS.
06-24-2021 10:14 AM [AppRunner] Service creation started.

After about 10 minutes get status:
Status
Create failed

Thank you, really liking where this service is headed ...

**Comment by sinedie** [comment]
same here, but with github connection.

**Comment by pprahlad** [comment]
Can you please open a support ticket with the ARN of the service you were trying to create? We are adding more to those log messages to help you decipher these workflow failures directly.

**Comment by amgci** [comment]
Do you have a link for the ARN for opening a support ticket?

Thanks, Kipp

-- 
Kipp Wright, CTO/COO
AmgeePub
207-706-6100

CONFIDENTIAL: The information contained herein including, but not limited to, 
any attachments, hyperlinks or other material is PROPRIETARY and considered a 
TRADE SECRET of AMGCI, LLC., and/or its subsidiaries, affiliates, 
licensees and should not be disclosed to any person who does not have a need to 
know such information.
