### ISSUE TITLE
Support configuration of HTTP health checks from the console

### ISSUE THREAD

**Issue by cou929** [aws/apprunner-roadmap#63]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I want to run a containerized application, which image is pushed to ecr, on App Runner that already has an HTTP health check endpoint implemented.
However, there is no item in the console to set the HTTP protocol health check.

**Describe alternatives you've considered**
I want you to be able to configure the health check of HTTP protocol from the AWS console.
Currently configurable only TCP protocol on console.

**Additional context**
We can configure it using the AWS CLI ([aws apprunner create-service](https://docs.aws.amazon.com/cli/latest/reference/apprunner/create-service.html)), but I want also be able to configure it from the console.

**Attachments**
Only TCP health checks supported on console.
![image](https://user-images.githubusercontent.com/25668/125956321-64d96d9f-30de-49b3-9f7c-431915f802cc.png)

**Comment by PatrickGotthard** [comment]
In addition it is not possible to update the autoscaling configuration from the console - at least when using a custom check path.
Our application logs indicate that the health checks will be performed on "/" instead of the previously configured path when trying to update the config.

**Comment by snnles** [comment]
Hello everyone, Now you can configure HTTP health checks from App Runner console. You can also update your service configuration without overriding health check configuration. Our documentation will be updated soon.

Thank you for your feedback!
