### ISSUE TITLE
AppRunner Custom Domain limitation on APEX domain

### ISSUE THREAD

**Issue by ttirtawi** [aws/apprunner-roadmap#65]
When we added custom domain,  the instruction from the console isn’t quite clear for 2 reasons:

1. The instruction mentioned to add 2 records, but the table show 3 records.
2. For the DNS Target one, it didn’t take the account the limitation of creating CNAME on APEX domain. So it gives misleading instruction to create CNAME on the apex domain. (ref:  RFC 1912)

![image](https://user-images.githubusercontent.com/3819534/126947942-da544c80-bb03-406b-b91b-7216dcc4bb33.png)

Suggest to give better instruction especially when user use apex domain, as CNAME will not work anyway.

**Comment by joswayski** [comment]
+1

Would be ideal if they were auto created like when ACM creates records for you

<img width="919" alt="Screen Shot 2021-08-03 at 11 21 13 AM" src="https://user-images.githubusercontent.com/22891173/128041683-09d3c9de-38e2-4794-b1c4-6800339f9a04.png">

**Comment by Sitole** [comment]
How can i create APEX domain record for App Runner linked domain?
I want to connect xyz.com domain hosted on Route 53 with App Runner but CNAME for APEX domains is not possible.

**Comment by rajanvalencia** [comment]
> How can i create APEX domain record for App Runner linked domain?
> I want to connect xyz.com domain hosted on Route 53 with App Runner but CNAME for APEX domains is not possible.
> 
> Any ideas? :/

You can’t do it in the meantime

**Comment by bessiambre** [comment]
Anyone know what are the "better instructions"? I can't seem to get this working.

**Comment by Sitole** [comment]
> 

I just setup App Runner domain for www.xyz.com and then create CloudFront distribution associated with xyz.com.
Cloudfront just redirects uses from APEX to www.xyz.com. It works but its complicated. I want direct support of APEX domain in App Runner.

**Comment by bessiambre** [comment]
Hi thanks for the answer! Now I can't seem to be able to pull off the first part or setting up the App Runner domain for  www.xyz.com. App Runner seems to only allow me to enter a naked domain.

Now I do see that the documentation states: "You can optionally include the www subdomain of your domain. However, this is currently only supported in the API. The App Runner console doesn't support it."

Does that mean there is no way to configure DNS from the console and the UI there is just a placebo?

**Comment by Sitole** [comment]
> 

You can configurate DNS directly from AWS Console. The message about "www" means in API you can use something like `alsoCreateWwwDnsRecord: true` and then you can request just `xyz.com` and www record will be created automatically. In AWS Console you must create two separated requests.

**Comment by bessiambre** [comment]
Thanks again for the help. If I click on "Link Domain" in the console there is a popup that lets you enter the domain name, but it will not let you prepend a subdomain. The text field just deletes characters.

[edit] Oh wait, maybe it's letting me now. I got confused because there seems to be code that runs every 10 or 15 seconds that deletes characters out of the input field. It seemed to be removing the 'www' I was trying to write. If I write the whole thing and click withing like 10s, I seem to be able to create it. It must be some glitch in the interface. Putting this here in case others are struggling. The trick is to write your domain and click fast!

**Comment by csuna-chen** [comment]
https://docs.aws.amazon.com/apprunner/latest/dg/manage-custom-domains-route53.html
Hi Right now Apprunner supports Route53 Alias record, which enables you to create APEX domain

**Comment by snnles** [comment]
> https://docs.aws.amazon.com/apprunner/latest/dg/manage-custom-domains-route53.html Hi Right now Apprunner supports Route53 Alias record, which enables you to create APEX domain

This feature is supported in App Runner now. Launch announcement:
https://aws.amazon.com/about-aws/whats-new/2022/09/aws-app-runner-supports-amazon-route-53-alias-record-root-domain-name/

**Comment by jellevdvliet** [comment]
Does this have to be enabled or something? I can't select an app runner alias for my domain

**Comment by csuna-chen** [comment]
Hi, jellevdvliet, have you follow up the instruction on public doc, basically you should 
1.  Go to Route53 console
2. Choose the name of the hosted zone that you want to use
3. Choose Create record. 
4. In Value/Route traffic to: Choose Alias to App Runner Application, then choose the Region that the endpoint is from. Choose the domain name of the application that you want to route traffic to. 
5. ......(see the detail in doc https://docs.aws.amazon.com/apprunner/latest/dg/manage-custom-domains-route53.html)
