### ISSUE TITLE
Allow limit increases for App Runner such as Auto Scaling MaxSize

### ISSUE THREAD

**Issue by jeremyjpaws** [aws/apprunner-roadmap#67]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like to be able to increase the max size (max container instances) of my service beyond the current limit of 25. Currently, this is not an adjustable limit.

**Comment by CristianLlanos** [comment]
Have you tried creating a new case in the Support Center? There is a "Service limit increase" option and there is an option for AppRunner in there.
https://console.aws.amazon.com/support/home#/case/create

**Comment by snnles** [comment]
Hello everyone, thank you for your feedback. You can now increase the auto-scaling maximum instance limit for your account by raising a support ticket.
