### ISSUE TITLE
Add the ability to filter application logs based on time.

### ISSUE THREAD

**Issue by jsheld** [aws/apprunner-roadmap#68]
Customers should have the a ability to filter application logs based on time criteria, e.g., last year, between two dates, etc.

**Comment by toricls** [comment]
It's available now in the management console! 🚀

![Relative range](https://user-images.githubusercontent.com/3761357/131927398-82207246-a88a-478c-88e6-64b17185769a.png)
![Absolute range](https://user-images.githubusercontent.com/3761357/131927407-a3ae0fde-b95c-4840-8523-62310cfd6dd2.png)
