### ISSUE TITLE
CDK Integration

### ISSUE THREAD

**Issue by RichiCoder1** [aws/apprunner-roadmap#7]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
As an extension of #5, the ability to use the CDK to build and deploy an App Runner services like you can with Lambda Container CDK today.

**Comment by akshayram-wolverine** [comment]
L2 CDK construct for an App Runner service object has been merged: https://github.com/aws/aws-cdk/pull/15810
