### ISSUE TITLE
Allow service-based CPU/memory statistics

### ISSUE THREAD

**Issue by sitole** [aws/apprunner-roadmap#72]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Right now App Runner allows us to show only per-instance CPU and memory statistics. But for better context (we have multiple instances running in same time) i want to see per-service CPU and memory statistics in CloudWatch. So i can create Alarms etc. For example same as ECS services. Maximal, avg and minimal CPU/memory in some point of time.

**Comment by jvisker** [comment]
I think this just launched: https://aws.amazon.com/about-aws/whats-new/2023/02/aws-app-runner-concurrency-cpu-memory-utilization-metrics/

**Comment by snnles** [comment]
Hello everyone, App Runner now emits service based CPU utilization and Memory utilization metric in App Runner Console and Amazon CloudWatch. See the launch announcement for more details.
https://aws.amazon.com/about-aws/whats-new/2023/02/aws-app-runner-concurrency-cpu-memory-utilization-metrics/
