### ISSUE TITLE
Option to make App Runner only accessible for developers

### ISSUE THREAD

**Issue by FerhatPflegia** [aws/apprunner-roadmap#73]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Next to our production build, we want to run a staging build online which should be only accessible for certain people and not everyone. It would be great to have something so we can gatekeep the staging version. HTTP Basic Authentication would already suffice, but any method to lock the access to the App Runner would be welcome.

**Describe alternatives you've considered**
I tried to add Basic HTTP Authentication to our app but that only works for each page individually and only if we use server-side rendering (it is a NextJS app). I looked for alternatives but didn't find anything useful

**Comment by rhbecker** [comment]
Seems like this could be satisfied via issue #2?

**Comment by snnles** [comment]
App Runner now supports private services. You can now limit the accessibility of your App Runner services inside your VPC.

https://aws.amazon.com/about-aws/whats-new/2022/11/aws-app-runner-supports-privately-accessible-services-amazon-vpc/
