### ISSUE TITLE
boto3 NoCredentialsError() and How to use print to log (Python)

### ISSUE THREAD

**Issue by Jun711** [aws/apprunner-roadmap#74]
Hi, it is not really a feature request but I encountered some issues and need some help. Thank you

1) I am using boto3 to access s3. I added permission to access s3 to the app runner role but when I got NoCredentialsError. Do I have to hardcode my credentials?
<img width="634" alt="Screen Shot 2021-09-17 at 7 13 11 PM" src="https://user-images.githubusercontent.com/6880939/133868954-42d46a3b-1948-479a-9211-2e14970c42fc.png">

2) my python print statements in the flask app don't seem to be passed to the stdout. Do I have to use logging instead?

**Comment by toricls** [comment]
Hi @Jun711.

1. I still need more info on the problem to go deeper, but I think you might added that permissions to a wrong IAM role.
In App Runner there are two user-created IAM roles for App Runner service one is [`Access role`](https://docs.aws.amazon.com/apprunner/latest/dg/security_iam_service-with-iam.html#security_iam_service-with-iam-roles-service.access) and another is [`Instance role`](https://docs.aws.amazon.com/apprunner/latest/dg/security_iam_service-with-iam.html#security_iam_service-with-iam-roles-service.instance). The `Access role` is for App Runner itself to allow App Runner to pull your container image from Amazon ECR at this moment, and the `Instance role` is for your application to allow your application to access AWS services such as S3.
So the point is that you need to create an `Instance role` (if not yet) and add the permissions to it, then set the instance role to your App Runner service. In the App Runner management console, it's under `Security` as the below screenshot. See also the [official docs](https://docs.aws.amazon.com/apprunner/latest/dg/security_iam_service-with-iam.html#security_iam_service-with-iam-roles-service.instance) to know how to create it.

![image](https://user-images.githubusercontent.com/3761357/134255582-f5a9c18c-ab1e-4e48-be33-9376f078892f.png)

2. I think it's recommended to use any logging mechanism if you're writing production app. It looks there is a [built-in logger](https://flask.palletsprojects.com/en/2.0.x/logging/) in Flask for example.
But in the meantime for testing App Runner purpose, I think you can just redirect your `print` output to stdout and stderr by:

```python
import sys

print('This goes to stdout', file=sys.stdout)
print('This goes to stderr', file=sys.stderr)
```

**Comment by toricls** [comment]
I'm closing this issue since this is not a feature request, but feel free to add further comments :)

**Comment by Jun711** [comment]
@toricls 
I found the Security - Instance Role menu but it doesn't seem to pull any of my IAM role. Is that an UI bug? 
From the network, I can see that it gets roles from IAM successfully. 
So, I have to use the cli to set a role now, I guess? 

<img width="910" alt="Screen Shot 2021-09-22 at 12 55 02 PM" src="https://user-images.githubusercontent.com/6880939/134412724-f427a6ac-b6d4-4be8-9a2e-225452a9a1f9.png">

<img width="1110" alt="Screen Shot 2021-09-22 at 12 57 32 PM" src="https://user-images.githubusercontent.com/6880939/134413093-38d9abf6-15dd-4ef2-b010-160f4ac95816.png">

**Comment by toricls** [comment]
App Runner console only shows eligible IAM roles for. So as noted in my previous comment, your next step is to create an instance role by following the official docs then you'll see it in the console :)

**Comment by Jun711** [comment]
@toricls 
I ran a long task and it timed out with this message:
upstream connect error or disconnect/reset before headers. reset reason: connection termination 

Questions:
1) Is it configurable?
2) what is the upper limit? API Gateway timeout is 30 seconds

**Comment by toricls** [comment]
App Runner automatically scales down when your service is inactive which is evaluated based on its incoming traffic (HTTP requests). So basically you need to ping your app via the service endpoint periodically if you want to run long running tasks without scaling it down automatically.

**Comment by toricls** [comment]
Regarding timeout for handling a request on App Runner's managed load balancer is not configurable today. I think it was about 600 seconds in my personal tests few month ago, but am not 100% sure if that's even true now.

**Comment by Jun711** [comment]
@toricls It is weird then, I got this error message:
```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```
By a long task, I mean something that runs like 30 seconds plus. 
I tried it again today, it seems that if I run a long task after an idle period, I would get that error message. If I run a shorter task first, this long task would be able to finish. 
Have you heard of this issue before?

**Comment by Jun711** [comment]
@toricls 
Another question that I have is if I use the default 1vCPU and leave the concurrency as 100. would that be a problem? can 1 vCPU handle 100 concurrent requests? I am trying to configure concurrency at the moment.

<img width="641" alt="Screen Shot 2021-09-29 at 3 58 59 PM" src="https://user-images.githubusercontent.com/6880939/135359843-c4dfa756-7daa-4e30-b0d8-7b39de5e1745.png">
