### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by RichiCoder1** [aws/apprunner-roadmap#8]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Since the introduction of GitHub Actions, it's become a popular low-friction way to build and deploy applications. The integrated build experience of App Runner is awesome, but for companies on GitHub taking full advantage of it's features, they'll like err to using GitHub's native CI/CD. It'd be awesome to introduce an action like the [ECS](https://github.com/marketplace/actions/amazon-ecs-deploy-task-definition-action-for-github-actions) one that consumes the `apprunner.yml` and handles the deployment (and optionally build) of app runner services. Big pluses would be rich statuses and integration with GitHub's native deployment status.

**Comment by jvisker** [comment]
I think that this feature was released: https://aws.amazon.com/blogs/containers/deploy-applications-in-aws-app-runner-with-github-actions/

**Comment by RichiCoder1** [comment]
@jvisker I missed that blog post! I'm guessing this is still open since the actions is a Lab's project and not in the official org (yet).

For anyone coming into this issue now, the action in the blogpost above is <https://github.com/awslabs/amazon-app-runner-deploy>.

There's also the great Copilot CLI if you want something a bit more unified.

**Comment by snnles** [comment]
App Runner now supports GitHub actions. Refer to the public announcement for more details:
https://aws.amazon.com/about-aws/whats-new/2021/11/aws-app-runner-github-actions-build-deploy-applications/
