### ISSUE TITLE
Give support of  EFS (Elastic File Service) mount.

### ISSUE THREAD

**Issue by Gouravdeep** [aws/apprunner-roadmap#80]
Please give support of EFS  (Elastic File Service) mount.

**Comment by andymac4182** [comment]
I believe this will be pending support for VPC https://github.com/aws/apprunner-roadmap/issues/1

**Comment by RubberChickenParadise** [comment]
also duplicate of #14

**Comment by mwarkentin** [comment]
VPC support just landed, hopefully that unlocks this soon!

**Comment by bev-s** [comment]
Plus 1
