### ISSUE TITLE
X-Ray support

### ISSUE THREAD

**Issue by a-h** [aws/apprunner-roadmap#81]
**Tell us about your request**

I want to use X-Ray to track AWS API calls, and external HTTP requests.

**Describe alternatives you've considered**

I've tried running the X-Ray daemon inside the same container as my app, but ran into issues with DNS resolution randomly failing when the app starts up, which I think might be related, but am not sure yet.

**Additional context**

Ideally, it would be automatic - built into the service, and I wouldn't need to do anything special to run X-Ray except add the X-Ray code to my library, e.g. the AppRunner IAM role would be updated to be allowed to make X-Ray requests, and I wouldn't need to do anything about it.

**Comment by RichiCoder1** [comment]
@a-h I would check out https://aws-otel.github.io/ which is AWS's flavor of otel and includes a lot of DevUX and AWS-specific affordances.

**Comment by snnles** [comment]
This feature has been shipped. Refer to below What's New post for details:
https://aws.amazon.com/about-aws/whats-new/2022/04/aws-app-runner-x-ray-support/

**Comment by Negan1911** [comment]
Sounds great to have this! Just a small detail, I don't see any chance to configure it from CDK, it may not be available on CDK/Cloudformation yet?

**Comment by yimipeng** [comment]
Hi @Negan1911 thanks for asking. App Runner X-Ray feature is supported in [AWS CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-observabilityconfiguration.html) and [Copilot CLI](https://aws.github.io/copilot-cli/blogs/release-v117/) from the day of launch.

**Comment by Negan1911** [comment]
@yimipeng Ah, I think it's possible that CDK doesn't allow that right?

**Comment by RichiCoder1** [comment]
It's present in the CDK: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apprunner.CfnObservabilityConfiguration.html

It's just not exposed as an L2 in the Alpha package, so you have to do it the good ole fashion way.
