### ISSUE TITLE
Add Java Support

### ISSUE THREAD

**Issue by stoany09** [aws/apprunner-roadmap#84]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Describe alternatives you've considered**

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally identifiable information.)

**Comment by toricls** [comment]
Closing because we're tracking Java support in #16, thank you!
