### ISSUE TITLE
Unable to make my App Runner service scaling and create multiple instances

### ISSUE THREAD

**Issue by AlbertoSpinella** [aws/apprunner-roadmap#85]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
My ECR on App Runner service doesn't scale. Surely it's my lack of knowledge, but I tried different auto-scaling settings (default is 100-1-25, but I also tried 200-1-25 and 50-1-25). I tried different stress tests, but after few hundreds of requests it doesn't scale at all and lot of requests fail (reasons: connection timeout). As a reference, I use ddosify. The commands I run are:
`ddosify -t myhost.com -n 1000 -d 1000 -l linear`
`ddosify -t myhost.com -n 1000 -d 1000 -l incremental`
In the App Runner dashboard, if I go to Metrics, at the bottom I see the section "Active instances", and after my stress tests it never go over 1 instance.
What can I do to create multiple instances and let my service scale to multiple requests?

**Comment by qcam** [comment]
Encountered the same problem here. Tried changing the minimum size to 2+ but active instances in metrics kept staying at 1.

@AlbertoSpinella Would you be able to share how you resolved it?

**Comment by olivierpascal** [comment]
Yes, please share how you resolved it!

**Comment by mstoyanovv** [comment]
@qcam @olivierpascal check out the scaling configuration and make sure that the set 'Concurrency' will be handled by your instance. For example, if vCpu is set to 0.25 and auto scaling concurrency is set to 100 your instance will start failing before AppRunner starts scaling.
