### ISSUE TITLE
CloudFormation AutoScalingConfiguration Supprot For AppRunner

### ISSUE THREAD

**Issue by markotitel** [aws/apprunner-roadmap#88]
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently we cannot define AutoScalingConfiguration using CloudFormation

**Describe alternatives you've considered**
Custom Lambda resource

**Additional context**
N/A
**Attachments**
N/A

**Comment by hiebj** [comment]
So what is the actual answer here? Can we create AutoscalingConfiguration with CloudFormation? The documentation does not appear to have changed since @rhbecker commented on Jul 15, 2022.

Do we need to create a separate issue to update the documentation, or is this not officially supported?

**Comment by rhbecker** [comment]
@hiebj Just above your comment, there's an auto-generated notification indicating this issue was moved into the "We are working on it" column of the service's Roadmap - so, I think the answer is that it's not yet supported.

**Comment by Negan1911** [comment]
While the team is working in this, I did my own custom resource to use meanwhile, https://www.npmjs.com/package/cdk-apprunner-autoscaling If you use CDK you can use it. I'm quite sure there may be a way to achieve the same using play cloudformation code, let me know if you know how and we can work on it too!
